CrisisCleanup/crisiscleanup-4-web

src/models/Affiliate.ts, src/pages/organization/Affiliates.vue, src/pages/organization/routes.ts, src/store/database.ts
- feat(model): add affiliate
- feat(route): add affiliates
- feat(affiliates): convert to composition api
- fix(affiliate): make methods work
- fix(affiliates): typescript errors
- feat(affiliate): add organization select
N/A
Closes #12 
N/A
=> Migrate org 'Affiliates' page

env.d.ts, src/pages/OtherOrganizations.vue, src/router.ts
- feat(migrate): copy OtherOrganization related files from old repo
- feat(router): add route for `other_organizations` in router.ts
- feat(types): add env.d.ts for env var types
- feat(migrate): add typings + improve + migrate `/other_organizations` pages
- fix(pages): use getter fn for createdAtLteFilter in `OtherOrganizations`%
N/A
Closes #17
=> Migrate 'Other Organization` page

src/components/LayerUploadTool.vue, src/components/LocationTable.vue, src/models/Location.ts, src/models/LocationType.ts, src/pages/organization/Layers.vue, src/pages/organization/routes.ts
- feat(layers): add layer to the routes
- feat(affiliates): convert location table
- feat(layerUpload): finish converting to vue 3
- fix(layerUpload): post request%
Closes #13 
=> Migrate org > layer library page

src/pages/NotFound.vue, src/router.ts
- feat(pages): add `NotFound` page
Closes #20
=> Add `NotFound` 404 page

src/components/BaseSelect.vue, src/components/RequestRedeploy.vue, src/components/UserSearchInput.vue, src/main.ts, src/models/Organization.ts, src/pages/organization/Profile.vue, src/pages/organization/Users.vue, src/pages/organization/routes.ts
- fix(comps): fix issues with `UserSearchInput` component
- fix(pages): fix usages/issues with organization/Users.vue
- refactor(src): remove unwanted console logs
- feat(main): make all fas icons available in vue app
- feat(models): add approved_roles field on Organization model
- feat(pages): enable OrganizationProfile route
- feat(pages): migrate, add typings, fix issues in pages/organization/Profile.vue
- fix(pages): use base-select instead of form-select in org profile page
- fix(pages): pass correct input value for updating org
- feat(comps): split inline classes object into multiSelectClasses computed property
- feat(migrate): migrate, add typings, fix issues for `RequestRedeploy` component
- feat(models): add missing `approved_incidents` property on Organization model
- …
=> Migrate Org Profile page

src/components/BaseInput.vue, src/components/CapabilityItem.vue, src/components/SimpleMap.vue, src/components/Slider.vue, src/components/admin/incidents/NestedBuilderItem.vue, src/components/form/FormTree.vue, src/components/live/OrganizationActivityModal.vue, src/components/work/SectionHeading.vue, src/components/work/WorksiteActions.vue, src/components/work/WorksiteForm.vue, src/pages/admin/AdminCms.vue, src/pages/admin/AdminOrganization.vue, src/pages/unauthenticated/PewPew.vue
This fixes all the tooltips stylings and the click triggers
=> Tooltip Fix

src/models/Location.ts, src/models/Organization.ts, src/pages/Location.vue
This PR fixes type errors in location and issue with the radio button not working in location
=> Fix type errors

src/pages/OtherOrganizations.vue
- fix(pages): fix broken search on OtherOrganizations page
N/A
Closes #77
=> Fix broken search on OtherOrgs

.tool-versions, src/components/Table.vue, src/models/types/index.ts, src/pages/OtherOrganizations.vue, src/pages/organization/Invitations.vue
- feat(pages): rm axios usages + unused funcs
- chore(tools): bump pnpm to v7.29.0 in .tool-versions
- refactor(pages): use type import for Org model
- feat(comps): add + export `TableSorterObject` type, update sorter prop type in `Table`
- feat(pages): use TableSorterObject type in Invitations.vue, delete SorterObject type
- feat(pages): make all other org columns sortable
- feat(pages): add otherOrgSorterFunc for sorting columns, handle table change when sorting, cleanup component
- feat(models): add optional primary_state field on `Status` interface
- feat(comps): add TableColumnSearch, TableColumnFilters, TablePagination, TableChangeEmitItem types in `Table`
- feat(comps): set valid prop types for pagination and columnSearch in `Table`
- feat(comps): define list of emits for `Table`
- …
=> Fix Other Org col sorting + default sort by name

src/components/admin/AdminEventStream.vue
Add spacing between the organization name and the action
=> Admin event stream font stylings

src/hooks/useCapabilities.ts, src/pages/organization/Profile.vue, src/pages/organization/TeamDetail.vue
This PR fixes the issue with assigning cases to teams
=> Add Cases to Team in organization

src/components/phone/UpdateStatus.vue, src/pages/phone/PhoneSystem.vue
=> Phone Status fix

src/hooks/useApi.ts, test/unit/hooks/useApi.test.ts
- feat(hooks): add thenable success func on useApi hook, update typings
- docs(hooks): fix jsdoc params for useApi hook
- test(hooks): add unit tests for success method, update snapshots + mock useAxios func
- docs(hooks): add docs for using awaitable success func on useApi hook
@tabiodun Here is the updated usage with awaitable `success` function you requested that returns same reactive data.
I was going to name this method `then`, but this linting rule (https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-thenable.md) wasn't allowing it. Therefore, I named it `success`.
```diff
diff --git a/src/pages/OtherOrganizations.vue b/src/pages/OtherOrganizations.vue
index 9de11cc..378ac86 100644
--- a/src/pages/OtherOrganizations.vue
+++ …
```
=> Feat: Add awaitable success method on useApi

src/pages/OtherOrganizations.vue, src/utils/data_filters/WorksiteStatusGroupFilter.ts
- refactor(pages): remove unused styles on `OtherOrganizations`
- fix(pages): redirect to work instead of legacy cases page on cases overdue click
- fix(utils): fix typings in WorksiteStatusGroupFilter class
Ref #76
=> Other Org Case link fix

.eslintrc-auto-import.json, src/auto-imports.d.ts, src/pages/admin/AdminOrganization.vue, vite.config.ts
- feat(dx): use auto-import plugin to provide useApi hook globally, update autogenerated files
- fix(pages): reduce z-index for GroupSearchInput as a high value z-index is set on base-select :(
N/A
Closes #87
=> Fix bad admin org edit dropdown

src/components/BaseInput.vue, src/pages/organization/CreateTeamModal.vue
- feat(comps): define emits options on `BaseInput` component
- refactor(pages): use shorthand func call, avoid array cloning on filter as filter already clones array
- fix(pages): replace input w/ update:model-value for base-input usages to make search input work
- fix(pages): replace default ok action w/ close/create action buttons on `CreateTeamModal`
- refactor(pages): replace $http w/ useApi on saveTeam func
- refactor(pages): remove unused imports, set lang on <style>
- refactor(pages): remove dead code from CreateTeamModal
N/A
Closes #63
=> Fix Org assign cases

src/components/admin/incidents/IncidentForm.vue
- feat(comps): update format + enable seconds for datepicker w/ defProps in `IncidentForm`
- No seconds picker
- date formatting doesn't show time
- contains seconds picker
- update date formatting to `yyyy-MM-dd HH:mm:ss`
Closes #200
=> Admin: Update format + enable seconds picker in IncidentForm

src/components/admin/UsersTable.vue
- fix(admin): redirect to '/' instead of '/admin' when impersonating a user
Impersonating user using `Login As` from '/admin' redirects to '/admin'
Impersonating user using `Login As` from '/admin' redirects to '/'
N/A
Closes #203
=> Admin: Redirect to '/' instead of '/admin' when impersonating user

src/store/modules/acl.ts
- fix(acl): only allow `development_mode` rule in dev & staging env%
- `Debug User` and `Debug Incident Stats` show up in production
- `Debug User` and `Debug Incident Stats` no longer show up in production
N/A
Closes #195
=> Acl: Only allow `development_mode` rule in dev & staging envs

src/App.vue
- fix(app): only watch route.name to update page title based on nav name
- Document title wasn't updating with route changes
- Document title is now reactive and updates based on routes
N/A
Closes #192
=> App: Reactive Page Title

src/layouts/Home.vue, src/pages/unauthenticated/InvitationSignup.vue
- fix(pages): typescriptify component, remove unused export from setup fn
- fix(layouts): typescriptify `Home` layout
- fix(layouts): set z-50 on main container on `Home` layout to prevent z-index issues
N/A
Closes #212
=> Fix: Unclickable Accept Invite Btn

package.json
- Fix broken test scripts in package.json
N/A
N/A
=> fix(pkg): rm testing mode with vitest, use default test mode

.env.sample, .gitignore, README.md
- chore(git): fix env files config in .gitignore
- chore(env): add .env.sample
- docs: format + update env section of README
N/A
N/A
=> Add .env.sample & fix .gitignore

package.json, pnpm-lock.yaml, src/services/auth.service.ts, src/services/db.service.ts, src/services/geocoder.service.ts, src/types/parse-address/index.d.ts, src/types/pitney-bowes.d.ts, tsconfig.json
All notable changes to this project will be documented in this file.
- **services**: Fix typings by adding if guards + type castings in AuthService ([0c90df2](0c90df22c5fb5ed42081bb3cf6e77fc1cb16da20))
- **types**: Fix invalid types caused by PB prefix in pitney-bowes.d.ts ([9d82988](9d82988ab3f17fb8a52d8c99ef7357023b7a1822))
- **types**: Add missing types in auth service ([4af9930](4af993026cd3ed088ccbe3c5c165d8fb9b1f32e5))
- **deps**: Add @types/google.maps for global google object loaded from script tag, update lockfile ([ed65d0e](ed65d0e4cc8c67139239bd8ad522083eb57487e0))
- **services**: Add if guards with error messages for fixing types in geocoder service ([9371247](93712473cd94614457480ece97d6e46236f44c09))
- **types**: Add types for parse-address pkg …
=> Fix type errors in `src/services`

src/components/header/Header.vue, src/components/work/WorksiteView.vue
Fix broken header on site caused by forcing ts on all components.
N/A
N/A
=> Fix broken header component

src/components/EventTimeline.vue, src/components/work/CaseHistory.vue
https://github.com/CrisisCleanup/crisiscleanup-4-web/issues/130
=> feat: Upgrade Worksite History

src/pages/Profile.vue
- fix(pages): fix incorrect usage of updating uploading state preventing profile pic update
- fix(pages): remove remaining `this` usage from `Profile` to avoid future bugs
N/A
Closes #263
=> Fix broken profile image update functionality

package.json, pnpm-lock.yaml, src/components/live/CaseDonutChart.vue, src/components/live/LiveOrganizationTable.vue, src/types/d3/index.d.ts
- feat(d3): delete local type module for d3, add @types/d3 as replacement
- feat(pewpew): show total in center on `CaseDonutChart`, change chart options to make it better, update `LiveOrganizationTable`
N/A
Closes #185
=> Fix broken donut charts on pewpew page

postcss.config.cjs, src/components/BugReport.vue, src/components/IncidentContact.vue, src/components/live/D3BarChart.vue, src/components/live/TotalCases.vue, src/components/work/WorksiteView.vue, src/pages/phone/PhoneSystem.vue, tailwind.config.cjs, vite.config.ts
This PR also fixes the following vite warnings in console:
- Nested CSS warnings
```
[vite:css] Nested CSS was detected, but CSS nesting has not been configured correctly.
Please enable a CSS nesting plugin *before* Tailwind in your configuration.
See how here: https://tailwindcss.com/docs/using-with-preprocessors#nesting
```
- `::v-deep` & `>>>` selector warnings
```
[@vue/compiler-sfc] ::v-deep usage as a combinator has been deprecated. Use :deep(<inner-selector>) instead.
[@vue/compiler-sfc] the >>> and /deep/ combinators have been deprecated. Use :deep() instead.
```
See:
- https://github.com/tailwindlabs/tailwindcss/discussions/7035
- https://github.com/vuejs/rfcs/blob/master/active-rfcs/0023-scoped-styles-changes.md#deep-selectors
- chore(config): remove unused commented css config …
=> Feat: handle 'No current hotlines' when showing hotlines, minor refactors & fixes on other comps

index.html, package.json, pnpm-lock.yaml, src/App.vue, src/hooks/index.ts, src/hooks/useZendesk.ts, test/unit/hooks/useZendesk.test.ts
- feat(public): remove zESettings setup from index.html
- feat(deps): add `@vueuse/shared` as dependency
- feat(hooks): `zE` widget typings, `useZendesk` reactive config + `zE` instance exposure
- feat(hooks): export `useZendesk`, remove invalid exports
- feat(app): initialize and provide zendesk widget during app init.
- fix(hooks): hide zendesk help button until later initialization via hook
Ref #306 @DatGamingStache 
=> feat(hooks): `useZendesk` reactive widget configuration typings, and api exposure

src/components/BaseButton.vue, src/components/BugReport.vue, src/components/FileUpload.vue, src/components/SimpleMap.vue, src/components/Spinner.vue, src/components/Table.vue, src/components/modals/ChangeOrganizationModal.vue, src/components/wizard/Wizard.vue, src/components/work/WorksiteImageSection.vue, src/layouts/Authenticated.vue, src/layouts/page/Page.vue, src/pages/Dashboard.vue, src/pages/Location.vue, src/pages/admin/AdminDashboard.vue, src/pages/admin/AdminOrganization.vue, src/pages/admin/Report.vue, src/pages/admin/Reports.vue, src/pages/unauthenticated/PewPew.vue, src/pages/unauthenticated/PrintToken.vue
https://github.com/CrisisCleanup/crisiscleanup-4-web/issues/291
=> feat: Add Witticisms whenever the spinner is loading

src/hooks/useSetupLanguage.ts
https://github.com/CrisisCleanup/crisiscleanup-4-web/issues/313
=> Fix: If ... else en-us

src/App.vue, src/hooks/useZendesk.ts, src/layouts/Authenticated.vue
- feat(hooks/zendesk): reactively track ref to zendesk web widget iframe
- feat(hooks/zendesk): implement `ContactFormField.hidden` config
- feat(app): init ccu user id hidden zendesk field
- feat(layouts): prefill zendesk contact form with authed user info
=> feat(hooks/zendesk): Implement hidden zendesk fields, prefill user information

src/setupTests.ts, test/unit/components/AjaxTable.test.ts, test/unit/components/admin/OrganizationsTable.test.ts, test/unit/hooks/useZendesk.test.ts
@tabiodun I have fixed tests broken by the this commit (https://github.com/CrisisCleanup/crisiscleanup-4-web/commit/6c06e3d99d06fe09860e159189a45db4212ac31a). I have installed i18n & Vue3Mq globally on setupTests script to fix the issue. Please let me know if these changes cause any side effects on other tests. Thanks!!
- test(setupTests): update mock for vue3-mq, add factory mock using actual import (bce54c7)
- test(setupTests): install i18n & Vue3Mq plugins globally on tests (44cdd3f)
- test(unit/comps): setup common stubs for components for OrganizationsTable.test.ts (5e4d73e)
- test(unit/hooks): update broken snapshot for useZendesk.test.ts (c1a88e5)
- test(unit/comps): remove vue3-mq mock as it's defined globally now (95f083f)
- test(unit/comps): setup globalOptions for AjaxTable …
=> fix: Fix broken tests mainly caused by mq usage in Table component

test/globalSetup.ts, test/helpers.ts, test/setupTests.ts, test/unit/components/AjaxTable.test.ts, test/unit/components/admin/GhostUsersTable.test.ts, test/unit/components/admin/IncidentApprovalTable.test.ts, test/unit/components/admin/InvitationRequestTable.test.ts, test/unit/components/admin/InvitationTable.test.ts, test/unit/components/admin/OrganizationApprovalTable.test.ts, test/unit/components/admin/OrganizationsTable.test.ts, test/unit/components/admin/UsersTable.test.ts, test/unit/components/chat/Chat.test.ts, vite.config.ts
- feat(test/helpers): add commonComponentStubs helper
- refactor(test/unit): use commonComponentStubs in AjaxTable.test.ts
- refactor(test/unit): use commonComponentStubs in GhostUsersTable tests, fix warnings
=> fix: fix broken tests in CI/CD

src/components/BaseInput.vue, src/components/SimpleMap.vue, src/components/accordion/Accordion.vue, src/components/accordion/AccordionItem.vue, src/components/dialogs/ComponentDialog.vue, src/components/dialogs/SelectionDialog.vue, src/components/phone/Agent.vue, src/components/phone/PhoneComponentButton.vue, src/components/work/WorksiteActions.vue, src/components/work/WorksiteTable.vue, src/layouts/Authenticated.vue, src/pages/Dashboard.vue, src/pages/OtherOrganizations.vue, src/pages/Profile.vue, src/pages/Work.vue, src/pages/organization/Index.vue, src/pages/phone/PhoneSystem.vue
=> feat: Mobile specific views for crisiscleanup

.github/workflows/main.yml, package.json, pnpm-lock.yaml, vite.config.ts
=> feat: Setup CodeCov

src/components/Tickets/TicketCards.vue, src/components/incidents/IncidentList.vue, src/pages/admin/ZendeskTicketDashboard.vue
Please check syntax for table column headers.
=> Update ticket dashboard localizations

.github/workflows/e2e.yml, .github/workflows/main.yml, playwright.config.ts
=> feat: E2E Workflow improvements

.github/workflows/deploy.yml, .github/workflows/e2e.yml, .github/workflows/main.yml
- ci(main): use matrix.project key to generate playwright report artifacts based on browser type (56b6bed)
- ci(main): disable playwright DEBUG var for less verbose output in ci (71f1f67)
- ci(main): update name for install deps in main workflow (91c0327)
- ci(deploy): add options & type on deploy workflow_dispatch stage input (8da4a75)
- ci(e2e): update name for e2e.yml (61941d3)
- ci(e2e): set workflow_dispatch to allow running action manually (0a27d88)
- ci(e2e): add inputs to workflow_dispatch & skip/continue workflow if some inputs are set to false (0fff7c6)
=> feat: Workflow improvements

.github/workflows/e2e.yml, playwright.config.ts
- feat(config): skip webserver start w/ PW_SKIP_WEBSERVER env var (6620252)
- ci(e2e): add setup common env step w/ PW_SKIP_WEBSERVER=1 to not run local webserver (6e6a0a0)
- ci(e2e): skip slack notify for now (f129d3a)
- ci(e2e): use prod test app login creds for staging env setup (633af52)
- ci(e2e): add project to matrix to generate all combinations for browser x stage (ba51079)
=> fix: e2e workflow fixes

src/App.vue, src/components/Tickets/TicketCards.vue, src/layouts/Authenticated.vue, src/pages/admin/ZendeskTicketDashboard.vue
**Fixes and Enhancements:**
- Assigning tickets no longer deletes text in ticket reply.
- Applying a macro now appends to a ticket reply instead of replacing.
- Setting status to anything but open (pending/solved) results in the modal closing now.
- Only show "Show More" and "Show Less" if the description length is more than the raw subject.
- Fixed ticket table columns: added assignee (agent) to the table, decreased the size of the description column, changed "description" to "subject" for truncation and better use of space, and added a dash for null values.
- Removed current user spam console log from app.vue.
- Hide app type from the request form and prefill "web"
=> fix(tickets): QoL ticket imrpovements

test/setupTests.ts, vite.config.ts
=> fix: another attempt at fixing tests in CI

src/components/Modal.vue
- feat(comps): add toggle fullscreen feature on `Modal` w/ allowFullScreen & fullscreen props (a607863)
- fix(comps): remove deprecated native click modifiers in Modal (5e9d28a)
- feat(comps): define emits for Modal (5453964)
=> feat: Full Screen options for Modal

src/components/Tickets/TicketCards.vue, src/pages/admin/Index.vue, src/pages/admin/ZendeskTicketDashboard.vue, src/pages/admin/routes.ts
-add numbers to bugs and tickets on admin view 
-mobile optimization for ticket table and ticket cards
-fixed geo location for geo address linking to google
=> fix(tickets): Mobile Optimization and small feature changes

playwright.config.ts, test/e2e/pages/login-page.test.ts
=> fix: Fix errors in E2e tests in CI

src/components/work/WorksiteForm.vue
Tobi, I'm pretty sure this is how to change the default Auto Contact Frequency, because changing the order didn't help.
=> Change Auto Contact Frequency Default

.github/workflows/e2e.yml, .github/workflows/main.yml
- ci(e2e): make chromium binary available on e2e.yml just like main.yml (3a14b53)
- ci(e2e): set admin creds for dev, staging, & prod in e2e.yml (df7edc2)
- ci: use single quote when setting GITHUB_ENV to avoid resolving special chars in main & e2e workflows (7d01d89)
- ci(e2e): fix action-slack-notify version as it's unable to notify in current version (5202b57)
=> fix: Fix E2E staging & prod tests caused by special chars in secret

test/unit/components/chat/ChatMessage.test.ts
- test(unit): use data-testid for finding favoriteStar in `ChatMessage` test (21ac9fb)
- fix(tests/unit): fix lint + type errors in ChatMessage.test.ts (978072a)
=> fix: ChatMessage test fixes

src/layouts/Authenticated.vue
Signed-off-by: Braden Mars <bradenmars@bradenmars.me>
TypeError
Works
=> fix(layouts.auth): missing optional chain on index accessor

.github/workflows/e2e.yml, .github/workflows/main.yml, test/e2e/pages/dashboard.test.ts, test/e2e/pages/login.test.ts, test/e2e/pages/user-profile.test.ts
- ci(main): enable sharding with 4 shards in main e2e workflow (3dd9863)
- ci(e2e): enable sharding in e2e workflow (bedb236)
- ci(e2e): set shardIndex & shardTotal to 1 for webkit tests (faa4bb7)
- Revert "ci(e2e): set shardIndex & shardTotal to 1 for webkit tests" (5d6acfa)
- Revert "ci(e2e): enable sharding in e2e workflow" (6870745)
- test(e2e): increase test timeout on link status tests (ce8b857)
- test(e2e): reenable show/hide password with eye icon test (51654d1)
- test(e2e): add e2e data-testids test for user-profile page (f643db6)
=> feat: Faster E2e Tests with sharding, add user-profile tests

src/components/BaseSwitch.vue, src/pages/unauthenticated/Survivors.vue
https://github.com/CrisisCleanup/crisiscleanup-3-api/issues/723
=> feat: Ask Permission from Survivors to Share Images

src/components/modals/RedeployRequest.vue, src/layouts/Authenticated.vue
https://github.com/CrisisCleanup/crisiscleanup-4-web/issues/363
=> feat: Add Deployed Incidents to "Redeploy Request"

.github/workflows/e2e.yml, .github/workflows/main.yml, .gitignore, playwright.config.ts, test/e2e/auth.setup.ts, test/e2e/basic.spec.ts, test/e2e/pages/dashboard.test.ts, test/e2e/pages/login.test.ts, test/e2e/pages/myOrganization.test.ts, test/e2e/pages/otherOrganizations.test.ts, test/e2e/pages/reports.test.ts, test/e2e/pages/training.test.ts, test/e2e/pages/user-profile.test.ts, test/e2e/pages/work.test.ts, test/e2e/utils.ts
- feat(config): use separate setup configs for browsers with specified devices in playwright.config.ts (0fb313f)
- ci: don't cache + install chromium binary when running playwright tests since we use same browser for setup tests (1ebdc2b)
- chore: ignore blob-report dir from .gitignore (5573e1d)
- feat(config): use blob reporter in CI for playwright tests (0bf81b2)
- ci: reduce playwright report artifact retention from 30 to 7 days (f44eca3)
- ci(main): update test-e2e to upload report blobs, add merge-e2e-reports job to merge blob reports into html report and make it available as downloadable artifact (a34f599)
- ci(e2e): generate all-blob-reports from e2e, add merge-e2e-reports to generate html playwright report (a2a5f06)
- test(e2e/utils): use PW_TEST_TITLE_PREFIX env var to add prefix …
=> feat: E2e improvements, better test report generation

.github/workflows/deploy.yml, .github/workflows/e2e.yml
- ci(e2e): fix test title prefix for dev, staging, & prod env setup steps (8109929)
- ci(e2e): generate and merge separate e2e reports for different stages (18f15b2)
- ci(e2e): use SLACK_ICON secret in success & failure notify jobs (65df9f8)
- ci(deploy): add missing SLACK_ICON to action-slack-notify calls in deploy workflow (f1cd913)
- ci(e2e): fix name for upload html test report in e2e.yml (648f86f)
N/A
N/A
=> feat: CI Improvements

src/components/work/WorksiteForm.vue, src/pages/Work.vue, src/pages/home/Map.vue, src/pages/phone/PhoneSystem.vue, src/pages/unauthenticated/PewPew.vue, src/pages/unauthenticated/Survivors.vue
https://crisis-cleanup.sentry.io/issues/4388612149/events/b85d30137af14b94bd6cfc8e41e5af1c/ https://crisis-cleanup.sentry.io/issues/4388599649/events/8f22751ab5ab4a2c82d4290a6ce66339/
=> fix: Sentry issues

.github/workflows/e2e.yml, .github/workflows/main.yml, test/e2e/pages/dashboard.test.ts, test/e2e/pages/login.test.ts, test/e2e/pages/myOrganization.test.ts, test/e2e/pages/otherOrganizations.test.ts, test/e2e/pages/reports.test.ts, test/e2e/pages/training.test.ts, test/e2e/pages/user-profile.test.ts, test/e2e/pages/work.test.ts, test/e2e/utils.ts
- test(e2e): remove authorize handling from e2e, do not wait on network idle, wait visible dashboard
- test(e2e): remove all usages of wait for networkidle, replace with wait for load event
- test(e2e): wait for login redirect to complete before performing login test ids tests
Waits for network idle in almost all tests.
This is directly advised against by playwright and in some (currently untested) places such as phone page (which performs polling) would never work.
=> test(e2e): replace all wait for networkidle events with wait for load events, auth improvements

.github/workflows/main.yml, package.json, playwright.config.ts, test/e2e/pages/dashboard.test.ts, test/e2e/pages/login.test.ts, test/e2e/pages/myOrganization.test.ts, test/e2e/pages/otherOrganizations.test.ts, test/e2e/pages/reports.test.ts, test/e2e/pages/training.test.ts, test/e2e/pages/user-profile.test.ts, test/e2e/pages/work.test.ts, test/e2e/utils.ts
- test(e2e): remove static test timeouts from all e2e tests causing tests to fail in dev env (2b42d11)
- feat(config): increase default test timeout for playwright tests from 30 secs to 1 min (cb515a5)
- feat(pkg): set e2e test timeout for dev stage to 3 min for test:e2e:development script in package.json (8dc15f8)
- ci: don't skip e2e tests for pull requests (c3274eb)
- feat(e2e/utils): add optional oauth authorize btn click in doLogin util (c819ba5)
- ci: remove e2e job referencing e2e.yml workflow from main.yml (f4512b7)
- ci: disable e2e tests for pull requests as dev is really slow at the moment (ac589d8)
N/A
N/A
=> feat: E2e test improvements, update config, improve timeouts

src/hooks/useZendesk.ts, test/unit/hooks/useZendesk.test.ts
Page could fail to load if zendesk widget is blocked or fails to load in some way.
The setup of zendesk via the `useProvideZendesk` hook in the app entrypoint could break due to an invalid expectation of `window.zE` always being eventually available.
If window.zE never becomes available, zE becomes no-op
=> fix(hooks/useZendesk): page could fail to load if zendesk is blocked or otherwise unavailable

package.json, pnpm-lock.yaml, src/App.vue, src/services/auth.service.ts, vite.config.ts
- fix(svc.auth): flush entire local storage when clearing auth
- fix(svc.auth): do not rely on client-side token revocation to succeed
- feat(vite): add mkcert plugin for local https
- fix(app): do not remove user on expiry, allow handling through auth failure
- fix(app): use default headers for portal/web url instead of async interceptor
- fix(app): only attempt reauth on first auth failure and enqueue all other failures for retry on re-auth success
Basically, its an avalanche of attempts to get a new token. The reason behind this boils down to the fact that given 10 concurrent requests to load a page (say dashboard), if all 10 go 401, then all 10 all start trying to revoke / obtain -> revoke / obtain -> revoke obtain cycle (repeating because often one requests causes a fresh new token …
=> fix(auth): Enqueue 401 failed requests for retry pending refresh attempt the initial failure only

src/pages/phone/PhoneSystem.vue
- fix(pages/phone): remove red color bg when no hotlines are available
- fix(pages/phone): port over download, print, flag, & share functionality from work page to phone page
Case header buttons don't work on phone page
Case header buttons now works on phone page
N/A
Closes #426
=> fix: Fix broken case header buttons on phone page

.github/workflows/main.yml, test/setupTests.ts
- ci(main): set timeout-minutes on lint, type-check, build, & test job
- test(setupTests): remove enableAutoUnmount afterEach call from setupTests.ts
=> ci: Fix unit tests in CI

src/pages/admin/ZendeskTicketDashboard.vue
…e numers while viewing tickets
=> feature(tickets): hotline numbers added to tickets

src/hooks/useTranslation.ts, src/utils/promise.ts
Use existing translations api for localizations
=> Add retries for cached gets

src/components/cards/TitledCard.vue, src/components/phone/PhoneComponentButton.vue
=> fix(leaderboard): defaulted dropdown to today, fixed some minor styling

src/pages/unauthenticated/Survivors.vue
Fix survivors page issues
N/A
Closes #443
Closes #444
=> fix: survivors page issues

src/components/UserTransferRequestTable.vue, src/pages/Dashboard.vue, src/pages/organization/Invitations.vue
- fix(comps): fix onMounted issues with UserTransferRequestsTable, pass loading prop from Dashboard usage
- feat(pages): show user transfer requests table on MyOrganization > Invitations page
Closes #446
Closes #447
=> fix: fix UserTransferRequests table, Add UserTransferRequests table to MyOrg

src/pages/home/RegisterOrganization.vue, src/utils/errors.ts
- fix(utils): fix getErrorMessage util
- fix(pages): handle same org name error + other errors on org register in RegisterOrganization
Closes #450 
=> fix: Org register error handling

public/.well-known/apple-app-site-association
Add file for associating iOS apps and intercepting specific links
=> Apple app association

.tool-versions, Dockerfile, package.json, test/e2e/pages/training.test.ts, vite.config.ts
- chore(build): bump pnpm from v8.6.12 to v8.7.4, bump pnpm in Dockerfile
- test(e2e): remove covid iframe youtube testid as it's removed from /training
- feat(config): disable mkcert in ci in vite.config.ts
- feat(pkg): increase e2e retries on dev to 4, decrease timeout to 150000
=> fix: E2e fixes, improvements

src/constants.ts, src/pages/Work.vue, src/pages/phone/PhoneSystem.vue, vite.config.ts
- feat(config): enable mkcert plugin, set server.https to false
- refactor: move INTERACTIVE_ZOOM_LEVEL to constants, update usages
- fix(phone): show zoom and other map buttons on phone page
N/A
Closes #457
=> fix: show zoom + other btns on phone page

src/components/work/WorksiteForm.vue
- fix(comps): show confirm popup before sending sms
- fix(work): setup dataPrefill watcher correctly to autofill phone num on incoming calls
Closes #460
Closes #461
=> fix: Autofill phone num when taking calls, show confirm on phone notify send on worksite create

src/components/work/WorksiteForm.vue
=> [Bug] High priority checkbox toggle not working properly

src/components/WorksiteLegend.vue
=> [Bug] Legend not showing by default

src/components/phone/UpdateStatus.vue
=> fix(phone): notes not clearing on complete call

src/components/phone/UpdateStatus.vue
=> fix(phones): improved complete call indicators

src/components/WorksiteLegend.vue
=> fix(legend): legend improvements

src/components/phone/PhoneIndicator.vue
=> feat(phones): added pulsing phone indicators for when taking calls

src/components/phone/UpdateStatus.vue, src/components/work/WorksiteNotes.vue
=> fix(notes): added toast notification for worksite notes

src/components/work/WorksiteSearchInput.vue
=> Revert "refactor(comps): remove unused css from WorksiteSearchInput"

src/hooks/worksite/useLiveMap.ts, src/hooks/worksite/useWorksiteMap.ts
Resolve worksite blinky worksites issue and performance issues.
=> fix(map): pixi overlay layers are never disposed of

package.json, pnpm-lock.yaml, src/components/work/WorksiteForm.vue, src/components/work/WorksiteSearchInput.vue, src/hooks/useRecentWorksites.ts, test/unit/hooks/useRecentWorksites.test.ts
- Revert "feat(comps): disable recent worksites temporarily till its stable in WorksiteSearchInput" (138c521)
- refactor(comps): rearrange setup members in WorksiteSearchInput (972a472)
- feat(comps): emit blur & focus events from WorksiteSearchInput (dd34049)
- fix(hooks): fix issues with useRecentWorksites (398b619)
- test(unit): add tests for useRecentWorksites hook (3dccd36)
- fix(hooks): fix recentWorksites sorting (98e44e8)
- fix(comps): improve + fix issues with WorksiteSearchInput recent worksites (928461d)
- feat(deps): add fuse.js dep, update lockfile (1d19854)
- feat(comps): add types, handle recent worksites filtering + other things in WorksiteSearchInput (4c43d30)
- fix(comps): reduce recent worksite search threshold for more precise search (b9e013b)
- refactor(comps): use …
=> feat: Recent worksites in WorksiteSearchInput

src/components/work/WorksiteReportSection.vue
- volunteer hours now correctly save
closes #488
=> fix(worksiteReports): fixed volunteer hours

src/components/navigation/NavButton.vue
=> fix(navbar): navbar double active

src/components/work/WorksiteForm.vue, src/components/work/WorksiteSearchInput.vue, src/pages/Work.vue, src/pages/phone/PhoneSystem.vue
- feat(comps): add newly created worksite to recents on saveWorksite in `WorksiteForm`
- feat(worksite): set use-recents on only search fields on work & phone, set default use-recents to false in WorksiteSearchInput
- fix(comps): filter recent worksites by current incident id
Ref: #496
=> fix: Fix issues with recent worksite feature

src/utils/helpers.ts, src/utils/worksite.ts
- refactor(utils/worksite): use cacheKeys var for set/get DbService operations
- fix(utils/worksite): use MD5 for generating hashCode for loadCasesCached
- fix(utils/worksite): use sortedQuery to generate hashCode in loadCasesCached
- fix(utils/worksites): fix & improve types, refactor to use loadCases
- feat(utils/helpers): add generateHash helper
- feat(utils/worksite): use generateHash helper instead of hashCode
- refactor(utils/worksite): rename updated & reconciled vars in loadCasesCached
N/A
N/A
=> feat: Improvements in `utils/worksite`

src/components/work/CaseHeader.vue
=> fix(work): worksite icons better and print indicators

src/layouts/Authenticated.vue
=> fix(layouts): order incidents by `start_at` instead of `id` for incident selector

src/components/IncidentAssetEditor.vue, src/components/admin/incidents/IncidentAssetBuilder.vue, src/models/types/index.ts, src/pages/AppDownload.vue, src/pages/unauthenticated/Disasters.vue, src/pages/unauthenticated/routes.ts
https://github.com/CrisisCleanup/crisiscleanup-4-web/issues/406
=> feat: Create "Disaster Info" Page

.eslintrc.cjs, src/components/modals/CompletedTransferModal.vue, src/hooks/useConnectFirst.ts, src/hooks/useSetupLanguage.ts, src/layouts/Authenticated.vue, src/models/types/index.ts, src/pages/Dashboard.vue, src/pages/phone/PhoneSystem.vue, src/services/i18n.service.ts, src/services/storage.service.ts, src/types/detect-browser-language/index.d.ts, src/types/vue3-mq/index.d.ts, src/utils/helpers.ts
- feat(types): add types for vue3-mq module
- fix(layouts): make some minor improvements to Authenticated layout
- fix(types): add types for detect-browser-language module
- feat(models): add CCUApiListResponse, PhoneDnisResponse, PhoneDnisResult types
- feat(hooks): use PhoneDnis types to set type for caller in useConnectFirst hook
- refactor(phone): refactor logic to update phone1 from caller.value
- fix(config): enable ignoreStatic on typescript-eslint/unbound-method in eslint config
- feat(utils): add getApiUrl helper func
- feat(types): add `LanguagesResponse` interface in models/types
- feat(services): add generic types in StorageService
- feat(types): add `LocalizationsCountResponse` interface in models/types
- fix(services): add typings in i18n.service.ts
- fix(hooks): add types + …
=> feat: App load time improvements 1

.dependency-cruiser.cjs, .eslintignore, .eslintrc.cjs, package.json, pnpm-lock.yaml, src/components/admin/incidents/IncidentAssetBuilder.vue, src/filters/index.ts, src/hooks/live/useSiteStatistics.ts, src/hooks/phone/useScripts.ts, src/hooks/useAcl.ts, src/hooks/useConnectFirst.ts, src/hooks/useSetupLanguage.ts, src/hooks/worksite/useLiveMap.ts, src/hooks/worksite/useWorksiteMap.ts, src/hooks/worksite/useWorksiteTableActions.ts, src/main.ts, src/models/Language.ts, src/models/Worksite.ts, src/models/types/index.ts, src/modules/i18n.ts, src/services/phone.service.ts, src/utils/data_filters/Filter.ts, src/utils/errors.ts, src/utils/helpers.ts
This pull request tackles the persistent issue of cyclic imports in our repository. These cyclic imports have been causing problems with running unit tests and potentially hiding issues related to resolution/import trees and tree shaking.
To identify and fix these cyclic import issues, I used the [Dependency Cruiser](https://github.com/sverweij/dependency-cruiser) tool and ESLint's `import/cycle` rule.
I've also added several scripts to the package.json file. These scripts create a dependency graph in different formats such as SVG, HTML, or Mermaid. For the best viewing experience, I suggest using the HTML format.
With this pull request, all cyclic import errors in our repository have been resolved, improving the overall quality and reliability of our codebase.
- chore(config): ignore …
=> fix: Fix dependency cycle errors with i18n & other imports

.github/workflows/e2e.yml
Update schedule for e2e workflow
=> CI: Update e2e schedule

.github/workflows/deploy-site.yml
Ref #537
Ref https://github.com/CrisisCleanup/infrastructure/pull/49
=> ci(deploy): add deploy workflow for infrastructure cloudfront web stack

test/unit/components/admin/AdminBugs.test.ts, test/unit/components/admin/GhostUsersTable.test.ts, test/unit/components/admin/InvitationRequestTable.test.ts, test/unit/components/admin/InvitationTable.test.ts, test/unit/components/admin/OrganizationApprovalTable.test.ts, test/unit/components/admin/OrganizationsTable.test.ts, test/unit/components/admin/UsersTable.test.ts, test/unit/components/chat/Chat.test.ts, test/unit/fixtures/router.ts
- test(fixtures): add `buildMockRouter` fixture with example usage
- test(chat): restore `global.WebSocket` after chat tests, mock vue-router
- test: use mock router fixture in all tests that currently require it
Many tests breaking due to usage of `useRouter` in authentication hooks.
Adds fixture to enable quick n easy mocking of vue-router.
Uses fixture/mock where needed in currently failing tests, although almost all of these components really should not be directly using `useCurrentUser` anyways.
Most need to be refactored to be dumb components that receive this information via props.
=> test(fixtures): implement vue-router test fixtures, use fixture where needed for existing unit tests

src/components/IncidentContact.vue, src/layouts/Home.vue, src/pages/admin/routes.ts, src/pages/home/routes.ts, src/pages/organization/routes.ts, src/pages/phone/routes.ts, src/pages/unauthenticated/routes.ts, src/router.ts, vite.config.ts
- fix(routes): lazy-load routes to allow for code-splitting during bundling
- fix(bundle): add manual group for downloads/incident assets builder due to static import, explicitly enable treeshaking
- fix(layouts/home): invalid css comments breaking css code-splitting and minification
- fix(components/IncidentContact): invalid css comments breaking css code-splitting and minification
=> perf: Lazy load all components, fix broken css minification, fix bundle code-splitting issues

public/.well-known/apple-app-site-association
Update Apple universal links app IDs
=> Update universal links app IDs

src/components/IncidentContact.vue, src/filters/index.ts, src/pages/OtherOrganizations.vue, src/pages/admin/ZendeskTicketDashboard.vue, src/pages/phone/PhoneSystem.vue, src/pages/unauthenticated/Disasters.vue, src/pages/unauthenticated/PewPew.vue
- fix(i18n): fix i18n issue on other org page
- fix(hotline): clean duplicated logic to get active hotlines for incidents
=> fix: I18n reactivity + active hotlines issues

.github/workflows/e2e.yml, .github/workflows/main.yml, .gitignore, package.json, playwright.config.ts, src/components/BaseInput.vue, src/filters/index.ts, src/layouts/Authenticated.vue, src/models/Incident.ts, test/e2e/authentication.test.ts, test/e2e/basic.test.ts, test/e2e/pages/dashboard.test.ts, test/e2e/pages/login.test.ts, test/e2e/pages/myOrganization.test.ts, test/e2e/pages/phone.test.ts, test/e2e/pages/work.test.ts, test/e2e/utils.ts, test/unit/components/__snapshots__/BaseInput.test.ts.snap, test/unit/filters/index.test.ts, test/unit/hooks/incident/useCurrentIncident.test.ts, test/unit/hooks/useRecentWorksites.test.ts
- fix(comps): nest required label under root div in `BaseInput` to set attrs on root div (7487ee5e)
- test(e2e): set secondary test tags on e2e tests (83208afd)
- test(e2e): fix should redirect from login if already logged in test (e3ccb303)
- feat(pkg): add test:e2e:primary script in package.json (c4fa8b3a)
- test(e2e): mark should login e2e test as fast (2ee2e5b9)
- feat(config): enable github reporter in ci for playwright e2e tests (99b8a367)
- ci(e2e): create github report from blob report for e2e test runs in e2e.yml & main.yml (755bb4ee)
- ci(main): run only primary e2e tests on PRs, remove webkit from matrix.project (06b20e25)
- test(unit/snapshots): update BaseInput test snapshots (a2195273)
- chore: add playwright markdown report.md to .gitignore (4d243897)
- ci(e2e): generate …
=> feat: Add tags to e2e tests, fix e2e tests, fix broken org profile page, add+fix unit tests, update CI

test/e2e/pages/dashboard.test.ts
=> test(e2e): use adminUserStatePath for DashboardPage e2e tests

public/.well-known/apple-app-site-association, src/components/AppDownloadBadges.vue, src/components/AppDownloadLinks.vue, src/pages/unauthenticated/MobileAppUserInvite.vue, src/pages/unauthenticated/routes.ts, src/utils/app_store_links.ts
- Adds Apple Universal link for user invite.
- Redirects to app store or shows badges to download app on page open.
=> Add mobile app user invite page

src/components/LocationTable.vue, src/components/admin/OrganizationsTable.vue, src/components/admin/UsersTable.vue, src/components/work/WorksiteFilters.vue
=> fix(i18n): fix localization issues on some pages/components

src/hooks/incident/useCurrentIncident.ts, src/hooks/incident/useRouteIncident.ts, src/hooks/incident/useUserIncident.ts, src/layouts/Authenticated.vue, test/unit/hooks/incident/useRouteIncident.test.ts
- feat(use/useIncident): implement `updateCurrentIncidentId` which will propagate incident id through either route or user states
- fix(layouts/auth): current incident id not updating if not found in route
- test(use/useIncident): add unit test to useRouteIncident
=> fix(use/useIncident): propagate current incident id update through either route or states

src/components/WorksitePhotoMap.vue, src/layouts/Authenticated.vue, src/pages/Dashboard.vue, src/pages/OtherOrganizations.vue, src/pages/Work.vue, src/pages/admin/Reports.vue, src/router.ts
Issue: On Photo View, when click the "Jump to Case", it goes to the map view, not the photo view. Should stay on photo view.
Issue: On dashboard, show only claimed, open cases so that people don't manually unclaim a bunch of closed cases.
Issue: Click "Other Organizations," and then change the incident, nothing happens.
Add incident id to all urls
Issue: The "Other Organizations" table is totally foobar: Changing "Per Page" does not seem to do anything.
=> Various issue fixes

src/pages/OtherOrganizations.vue, src/pages/Profile.vue, src/pages/unauthenticated/BlogPost.vue
Also fixed issue with updating emails on user profile
=> feat: port https://github.com/CrisisCleanup/crisiscleanup-3-web/pull/1519 to web-4

src/pages/Dashboard.vue
Signed-off-by: Braden Mars <bradenmars@bradenmars.me>
=> fix(dashboard): remove unneeded dashboard refresh causing update issues

package.json, pnpm-lock.yaml, src/components/MarkdownRender.vue, src/hooks/useRAG.ts, src/pages/admin/AdminRAG.vue, src/utils/helpers.ts, tailwind.config.cjs
- feat(deps): add type-fest
- feat(utils): implement `toCamelCase` utility
- feat(components/MarkdownRender): add h5/h6, add style to links
- feat(hooks/useRAG): implement `useRAGUpload` hook
- feat(admin/rag): layout improvements, implement file uploads
=> feat(rag): admin layout improvements + file uploads support

src/components/BaseIcon.vue, src/components/cards/TabbedCard.vue, src/components/header/Header.vue, src/constants.ts, src/hooks/useTabs.ts, src/layouts/Authenticated.vue, src/layouts/page/PageTabBar.vue, src/pages/admin/Index.vue
- feat(hooks/useTabs): migrate updated useTabs hook
- feat(components/cards/TabbedCard): migrate TabbedCard component
- fix(components/BaseIcon): fix improper prop type for `type`
- fix(constants): cast constants as const
- feat(layouts/page/PageTabBar): re-integrate `useTabs` with page tab bar
- fix(header): race condition for header rendering and route readiness
- fix(layouts/Authenticated): resolve current user unsub issues with hot reloading
- fix(pages/admin): use tab type in admin tabs
=> feat: migrate newer useTabs hook, add TabbedCard back, re-integrate with PageTabBar, various fixes

src/components/MarkdownRender.vue, src/hooks/useRAG.ts, src/pages/admin/AdminRAG.vue, test/unit/hooks/useRAG.test.ts
- feat(hooks/rag): accept conversationId and collectionId into useRag hook
- feat(pages/admin/rag): implement collections selector, chat overflow fix
- feat(components/markdownrender): add styling for ol/ul,li,li>p
=> feat(rag): collections context switching, conversational rag chats handling

src/hooks/worksite/useWorksiteMap.ts, src/models/types/index.ts, src/pages/Work.vue
feat: setup default map bounds for portal + use portal to hide or show svi slider
=> fix: make svi slider only available after 100 cases

src/components/cards/Card.vue, src/components/cards/TabbedCard.vue, src/components/cards/TitledCard.vue, src/layouts/page/PageTabBar.vue, src/pages/admin/AdminRAG.vue, test/unit/components/cards/card.spec.ts
- feat(components/card): add footer slot to card
- feat(components/cards/TitledCard): expose footer slot in titled card component
- feat(components/cards/TabbedCard): dynamic tabname-footer slots
- fix(layouts/page): remove overflow-auto from page tab bar
- fix(pages/admin/rag): overflow layout issues and improvements
=> fix(rag): layout fixes and improvements, card footers

test/e2e/pages/work.test.ts
- test(e2e): pick random worksite from samples on worksite create e2e test
- test(e2e): dont check muckOutCheckbox in worksite create test
=> fix: Worksite create e2e test

src/hooks/useRAG.ts, src/pages/admin/AdminRAG.vue, test/unit/hooks/useRAG.test.ts
- feat(hooks/rag): implement `useRAGWebSocket` to auto-provide or inject existing shared websocket state
- feat(hooks/rag): add new schema types in rag api
- fix(hooks/rag): do not reset upload state on execute
- feat(hooks/rag): utilize `useRAGWebSocket` in `useRAG`
- feat(hooks/rag): implement async document upload message handling in `useRAGUpload`
- feat(pages/admin/rag): properly handle multiple file upload
=> feat(rag): shared rag websocket state, new message schemas, async file upload notifications

src/hooks/useRAG.ts, src/pages/admin/AdminRAG.vue
- feat(hooks/rag): accept `fileIds` input to `submitQuestion`, use `CCUFileItem` type
- feat(admin/pages/rag): add checkboxes to files list, use for scoping collection
=> feat(rag): configurable collection file scope via checkboxes

.github/workflows/main.yml
=> feat: Generate PR comment with e2e test summary

src/layouts/Authenticated.vue
- fix(layouts): bring back fast load times by fetching current user incident before loading other page data (bd367944)
=> fix: Bring back faster load times on Authenticated layout

.github/workflows/e2e.yml, package.json, pnpm-lock.yaml
- feat(deps): deps add playwright-slack-report dep, update lockfile (5d3d7db4)
- ci(e2e): generate json report in merge all blob reports step (1727807b)
- ci(e2e): add step to send e2e report to slack (8edf45a3)
- ci(e2e): fix incorrect json-results arg for sending slack report step (5676f3e5)
- ci(e2e): use correct secret for slack oauth token (effe7d94)
- ci(e2e): add report name in slack e2e report (942ac9ef)
- ci(e2e): remove extra meta fields from slack e2e report (4ac43f41)
- ci(e2e): send e2e related slack messages to qa channel (d4a2842a)
=> feat: Slack e2e test report

.github/workflows/e2e.yml, playwright.config.ts
- ci(e2e): fix invalid json for cli config
- ci(e2e): generate artifact in matrix-outputs
- ci(e2e): tweak some cli config settings
- ci(e2e): use default slack reporter in playwright config to send messages
- Revert "ci(e2e): use default slack reporter in playwright config to send messages"
- ci(e2e): change playwright-slack-report cli config
- ci(e2e): cat out e2e json report
- ci(e2e): enable showInThread, increase maxNumberOfFailures for pw slack report config
=> fix: E2e workflow for slack reports

package.json, pnpm-lock.yaml, src/components/MarkdownRender.vue, src/hooks/useRAG.ts, src/pages/admin/AdminRAG.vue, test/unit/hooks/useRAG.test.ts
- feat(pages/admin/rag): do not specify file ids if using all files
- feat(deps): add highlight.js dep
- feat(components/MarkdownRender): add syntax highlighting and codeblock support
- feat(hooks/rag): update message schema types to expect camelCase, add conversation status field and error message type
- feat(hooks/rag): handle conversation message in progress + error status messages, handle rag error message via toast
- fix(pages/admin/rag): remove unused import
* Silent socket failures
* No in progress updates
* No response on generation failure
* Socket failures show as toast and report to sentry
* Pending updates are shown inline with chat (overwritten once answer has started)
* generation errors are shown as "*Error*: <error message>"
Please check the type of change your PR …
=> feat(rag): display rag socket failures, display pending updates and generation errors in chat, update message schemas to expect camelCase

src/components/MarkdownRender.vue, src/components/admin/rag/MessageTools.vue, src/hooks/useRAG.ts, src/pages/admin/AdminRAG.vue
- feat(components/MarkdownRender): add left padding to list items
- feat(hooks/useRAG): add types for tool messages, add tool messages to rag entries
- fix(hooks/useRAG): do not set timeout for document callback error messages
- fix(hooks/rag): set streaming message to false on finish callback
- feat(components/admin/rag/MessageTools): implement overlay for listing all documents utilized in ai response by file
- feat(pages/admin/rag): add info button to display files used in ai response when available
=> feat(rag): Display documents used in ai response via message tools overlay

src/hooks/useRAG.ts, src/pages/admin/AdminRAG.vue
- fix(hooks/useRAG): do not use shared axios state for file uploads/deletions
- feat(hooks/useRAG): sort documents by upload date
- fix(pages/admin/rag): freely upload files concurrently now
=> fix(rag): do not use shared axios state for file uploads/deletion

src/components/Tickets/TicketCards.vue, src/components/TreeMenu.vue, src/components/chat/ChatMessage.vue, src/models/User.ts, src/pages/Work.vue, src/pages/lists/AddFromList.vue, src/pages/organization/TeamDetail.vue, src/pages/organization/Teams.vue, src/pages/organization/Users.vue
feat: Add AddFromList compoment
feat: Fix botts api
=> feat: Support lists in teams and users

src/components/header/UserProfileMenu.vue, src/components/work/WorksiteFilters.vue, src/hooks/lists/useCreateList.ts, src/pages/Work.vue, src/pages/lists/ListDropdown.vue, src/pages/lists/Lists.vue, src/pages/lists/NewListForm.vue, src/utils/data_filters/WorksiteListsFilter.ts
Added new localizations for lists
=> Lists localizations

src/hooks/index.ts, src/hooks/useRAG.ts, src/hooks/useRAG.tsx, src/main.ts
Signed-off-by: Braden Mars <bradenmars@bradenmars.me>
=> feat(hooks/useRAG): use and update time ago from timestamps in document upload messages

test/e2e/pages/phone.test.ts, test/e2e/pages/work.test.ts
=> test(e2e): fix work & phone data-testid e2e tests

test/e2e/utils.ts
=> fix(e2e): wrap e2e tags in backticks to avoid mentioning random github users in test reports

src/App.vue, src/components/BaseIcon.vue, src/components/navigation/NavButton.vue, src/components/work/CaseHeader.vue, src/layouts/Authenticated.vue, src/pages/Work.vue, test/unit/components/__snapshots__/BaseIcon.test.ts.snap
- fix(comps): set justify-center on BaseIcon
- fix(layouts): remove random white border in Authenticated layout
- fix(pages.work): remove sync icon from update status button
- fix(app): fix global button disabled opacity by setting scoped styles on CaseHeader, move global styles to App.vue
- fix(comps.nav): show yellow bar on active nav button to right, increase bar's width
- feat(comps): add filter-primary to convert white icon into ccu primary yellow using css filters
- feat(layouts): set name on all routes in Authenticated layout
- fix(comps.nav): set isActive correctly, use isActive to change icon color to yellow
- refactor(comps): remove debug console log from NavButton
- fix(pages.work): make table view action buttons left aligned
- fix(comps): update filter-primary class in …
=> fix: Table + other ui improvements

src/components/navigation/NavMenu.vue, src/hooks/useRAG.tsx, src/pages/admin/AdminRAG.vue, src/utils/helpers.ts
- fix(components/navigation): `NavMenu` portal logo url sometimes breaking hot reload
- fix(utils/helpers): ensure data is available before trying to parse it in axios casing transform util
- feat(hooks/useRAG): implement method for deleting a conversation, add conversation meta
- feat(pages/admin/rag): add ui to conversations list for deleting existing conversations
=> feat(rag): conversations meta fields and ability to delete

src/components/cards/Card.vue, src/components/cards/TitledCard.vue, src/pages/admin/AdminRAG.vue, test/unit/components/cards/card.spec.ts
- feat(components/cards): add and expose `body-header` slot
- feat(pages/admin/rag): move chat input to top of `Chat` card and improve styling
- feat(pages/admin/rag): inline collections selector to chat title card
- feat(pages/admin/rag): use inline grid with min rows for chat messages
=> feat(rag): move input to top of card, improve styling / layout, inline collection selector

src/App.vue
=> fix(app): set page title dynamically using computed & useTitle hook in App.vue

.eslintrc.cjs, package.json, pnpm-lock.yaml, src/components/accordion/AccordionItem.vue, src/components/cards/TabbedCard.vue, src/hooks/useRAG.tsx, src/hooks/useTabs.ts, src/pages/admin/AdminRAG.vue
- feat(components/accordion): allow override of `AccordionItem` name via slot
- feat(hooks/useRAG): extend file interface with rag specific attrs, document branch interface
- feat(hooks/useRAG): add method for updating rag document virtual path
- feat(hooks/useRAG): documents tree computed from rag file virtual paths
- feat(hooks/useTabs): accept active index as maybe ref input prop
- feat(components/cards): TabbedCard `activeRecallKey` prop for optionally recalling active tab from local storage
- style(config): enable ecmaFeatures.jsx in `eslintrc`
- feat(deps): add `typescript-eslint-parser-for-extra-files`
- style(config): use `typescript-eslint-parser-for-extra-files` for vue files
- feat(pages/admin/rag): give files view slightly more space
- feat(pages/admin/rag): recall active …
=> feat(rag): RAG File Explorer

src/pages/admin/AdminRAG.vue
Signed-off-by: Braden Mars <bradenmars@bradenmars.me>
=> feat(pages/admin/rag): add search to rag files

src/components/DragDrop.vue, src/hooks/useRAG.tsx
- fix(DragDrop): reset dom files list to emit on subsequent uploads of the same file
- feat(hooks/useRAG): implement document action schemas, add cancel button to upload queue toasts
- fix(hooks/useRAG): resolve dismissed toasts no longer rendering updates
=> feat(rag): Document upload cancellation, `DragDrop` fixes

src/components/live/TotalCases.vue, src/pages/unauthenticated/PewPew.vue, src/utils/helpers.ts, test/unit/utils/helpers.test.ts
- **feat(pages): replace main stat color from blue to white**
- **feat(pages): remove blue hover text shadow from pewpew stats**
- **feat(pages): set sm font size for values on all sub stats on pewpew**
- **feat(pages): set font bold for all stat labels on pewpew**
- **fix(pages): fix global x & y scrollbar on pewpew page**
- **feat(utils): add getColorContrast helper util**
- **fix(comps): fix text color contrast in TotalCases chart**
=> feat: PewPew improvements

src/components/BaseButton.vue, src/components/BaseLink.vue, src/constants.ts, src/hooks/worksite/useLiveMap.ts, src/pages/unauthenticated/Survivors.vue, tailwind.config.cjs, test/unit/components/BaseButton.test.ts
Added variant to button component to have TEXT_DARK that has its own stylings to just be used for a darker link
=> Add Link Color Change to Button

src/components/modals/PhoneOutboundModal.vue, src/pages/phone/PhoneSystem.vue
=> feat(pages): change incident id on callback selection, load manual dialer from query params

src/components/Tickets/TicketCards.vue, src/pages/admin/ZendeskTicketDashboard.vue
This fixes the issue where the ticket card is problematic in laptop. This was fixed by setting the height value for the modal in the ticket modal allowing it to be scrollable.
=> Ticket Card Overflow

src/components/phone/PhoneNews.vue
This PR adds user guides to the news section. This does it by making an axios request for a tag for user-guide
=> Make User Guide in phone news

src/components/Tickets/TicketCards.vue, src/components/live/CardStack.vue, src/components/live/EventCard.vue
This updates the event cards in the pew pew stream in order to have specific data to show icon that matches the status of the event
=> Event Card Updates

src/App.vue, src/components/phone/PhoneNews.vue, src/components/phone/PhoneOverlay.vue, src/components/work/WorksiteFilters.vue, src/utils/worksite.ts
- **fix(utils): use debug for logging in worksite caching utils**
- **fix(app): fix global filter-gray css filter**
- **fix(comps): remove css transition from section tabs in PhoneOverlay**
- **refactor(comps): remove console logs**
- **fix(comps): fix update start date localization key in WorksiteFilters**
- **fix(comps): save date filters as iso strings instead of date objects which gets lost when saving user states**
=> fix: Fix broken worksite date filters

.eslintrc.cjs, package.json, pnpm-lock.yaml, src/components/DisasterIcon.vue, src/constants.ts, src/icons.ts, src/types/unplugin-icons.d.ts, src/utils/helpers.ts, tsconfig.json, vite.config.ts
- **feat(deps): add unplugin-icons dev-dep, update lockfile**
- **feat(config): add unplugin-icons vite & tsconfig**
- **fix(types): fix icon const types in constants**
- **feat(types): add type module for unplugin-icons**
- **feat(utils): add extractIconNameFromPath helper util**
- **fix(config): ignore import/no-unresolved rule for unplugin icon imports**
- **feat(icons): add icons module for unplugin icon imports**
- **fix(comps): use unplugin icons in DisasterIcon to load icon as svg instead of object**
- **feat(icons): add CCU_ICONS const & type in icons.ts**
- **fix(comps): add alt & title attr on easter egg icon in DisasterIcon**
Refs #771 
Closes #677 
=> fix: Fix disaster icons to use svg using unplugin-icons

src/layouts/Home.vue, src/pages/home/PersistentInvitationSignup.vue, src/pages/home/RequestAccess.vue
- **feat(layouts): add register slot on Home layout to allow other pages to override it**
- **fix(pages): hide register button on persistent invitation & request access pages by overriding register slot**
Closes #844 
=> fix: Remove register button from invitation/activation pages

package.json, pnpm-lock.yaml, src/components/DisasterIcon.vue, src/components/header/Header.vue, vite.config.ts
- fix(pkg): update clean command in package.json (3f38298f)
- fix(config): fix issues with vite config, make improvements (0a73857e)
- fix(config): set unplugin icons plugin compiler to vue3 (4f6703de)
- fix(config): remove mkcert plugin from vite config + deps (e6a278e6)
- feat(deps): add iconify/json dev-dep for unplugin icons (587b33ee)
- fix(config): update unplugin icons config in vite config (3b16a5b1)
- refactor(comps): use script setup in DisasterIcon component (7a35f7d4)
- fix(comps): add prop type for currentIncident in Header component (26dafdca)
=> fix: Broken tests

src/assets/icons/qrcode.svg, src/components/phone/Agent.vue, src/components/phone/ManualDialer.vue, src/components/phone/PhoneOverlay.vue, src/components/phone/PhoneToolBar.vue, src/constants.ts, src/hooks/useConnectFirst.ts, src/models/User.ts, src/pages/dashboards/DashboardPage.vue, src/pages/dashboards/DefaultDashboard.vue, src/pages/dashboards/PhoneVolunteerDashboard.vue, src/pages/phone/PhoneSystem.vue, src/router.ts
fix: Fix issue with clicking callbacks in new phone system
fix: Show inbound and outbound indicator
=> feat: Initial phone volunteer dashboard

src/hooks/useAuth.ts, src/pages/unauthenticated/OtpLogin.vue, src/pages/unauthenticated/routes.ts, src/utils/errors.ts
- **feat(utils): improve error handling in getErrorMessage helper util**
- **fix(utils): handle bad request where data is string edge case for error handling in errors.ts**
- **feat(hooks): add otp login types + helper methods in useAuth hook**
- **feat(pages): add OtpLogin unauthenticated page**
- **feat(pages): add /otp-login unauthenticated route**
=> feat: OTP Verification page, error handling improvements

src/components/phone/PhoneOverlay.vue, test/e2e/pages/login.test.ts, test/e2e/pages/phone.test.ts
- **fix(comps): fix incorrect zoom tag in PhoneOverlay**
- **fix(comps): set data-testids for all phone overlay sections in PhoneOverlay**
- **test(e2e): add testNeedHelpCleaningUp data-testid for login data-testid test**
- **test(e2e): add phoneOverlayActionTestIds for phone page data-testid test**
=> E2e test fixes with new UI changes

src/components/phone/PhoneOverlay.vue, src/components/work/WorksiteForm.vue, src/hooks/useAuth.ts, src/models/PhoneOutbound.ts, src/pages/admin/AdminIncidentWizard.vue, src/pages/phone/PhoneSystem.vue, src/utils/errors.ts
Summary
Hooks: Refactor OTP generation and token exchange in useAuth.ts. Errors: Handle 409 conflict status in errors.ts.
Phone System: Add conditional checks and save functionality in PhoneSystem.vue. Phone Overlay: Remove empty variant attribute in PhoneOverlay.vue. Worksite Form: Add error handling and return values in WorksiteForm.vue. Phone Outbound: Add Axios error handling in PhoneOutbound.ts. Admin Incident Wizard: Clean up incident data handling in AdminIncidentWizard.vue. Details
src/hooks/useAuth.ts
Introduce CodeResponse interface.
Rename functions for better clarity.
Implement OAuth2 token exchange.
src/utils/errors.ts
Add 409 status case to error handling.
src/pages/phone/PhoneSystem.vue
Add null checks for worksiteForm.
Introduce save option in confirmation dialog.
Adjust …
=> fix: refine OTP authentication flow and incident management

src/components/BaseInput.vue, src/components/chat/Chat.vue, test/unit/components/__snapshots__/BaseInput.test.ts.snap
- **BaseInput.vue**:
- Refactored template structure to improve label rendering logic by moving the `v-if` condition for required fields.
- Added additional event emits for 'blur', 'focus', and 'enter'.
- **Chat.vue**:
- Introduced FontAwesomeIcon component to indicate mobile users in the chat.
- Added a new div element to display a mobile icon for users who are online via the mobile app.
- Updated props and component imports to include FontAwesomeIcon.
- Modified logic to handle online users by distinguishing between all online users and mobile online users.
- Updated the WebSocket event handler to process online and mobile users separately and fetch their data accordingly.
=> Refactor BaseInput component structure and enhance Chat component functionality

.tool-versions, Dockerfile, package.json, pnpm-lock.yaml, src/components/BaseInput.vue, src/hooks/useAuth.ts, src/pages/unauthenticated/OtpLogin.vue
- **fix(comps): set $attrs on input field in BaseInput**
- **fix(hooks): export verifyOtp, update loginWithOtp in useAuth**
- **feat(pages): add selector for otp login w/ multiple accounts**
- **fix(pages): use descriptive label for picking accounts on otp login**
- **chore(deps): update pnpm to v9**
=> fix: OTP Login for multi accounts, e2e test fixes, pnpm v9 upgrade

src/pages/lists/NewListForm.vue, src/pages/unauthenticated/OtpLogin.vue
Make sure to re-implement the bug fix that does not pick the first entry.
=> Add OTP localizations

package.json, pnpm-lock.yaml, src/hooks/worksite/useRenderedMarkers.ts, src/types/kdbush/index.d.ts
Migrate KDBush from v3 to v4 following https://github.com/mourner/kdbush/releases/tag/v4.0.0
=> feat(deps): upgrade kdbush to v4, update usage from migration docs

src/models/Language.ts, test/setupTests.ts, test/unit/models/Affiliate.test.ts, test/unit/models/EventLog.test.ts, test/unit/models/Incident.test.ts, test/unit/models/Invitation.test.ts, test/unit/models/InvitationRequest.test.ts, test/unit/models/Language.test.ts, test/unit/models/Layer.test.ts, test/unit/models/Location.test.ts, test/unit/models/LocationType.test.ts, test/unit/models/Organization.test.ts, test/unit/models/PasswordResetRequest.test.ts, test/unit/models/PhoneOutbound.test.ts, test/unit/models/PhoneStatus.test.ts, test/unit/models/Report.test.ts, test/unit/models/Role.test.ts, test/unit/models/Team.test.ts, test/unit/models/User.test.ts, test/unit/models/UserRole.test.ts, test/unit/models/WorkType.test.ts, test/unit/models/Worksite.test.ts, test/unit/models/WorksiteRequest.test.ts, test/unit/models/base.test.ts
- **test(unit.models): add unit tests for User vuex orm model**
- **test(unit.models): add unit tests for Affiliate vuex orm model**
- **test(unit.models): add unit tests for EventLog vuex orm model**
- **test(unit.models): add unit tests for Incident vuex orm model**
- **test(unit.models): add unit tests for Invitation vuex orm model**
- **test(unit.models): add unit tests for InvitationRequest vuex orm model**
- **test(unit.models): add unit tests for Language vuex orm model**
- **test(unit.models): add unit tests for Organization vuex orm model**
- **test(unit.models): add unit tests for Team vuex orm model**
- **fix(models): move api call related funcs to apiConfig in Language model**
- **test(setup): add mock rest handlers for some language routes**
- **test(unit.models): fix issues …
=> feat: Vuex Model Unit Tests

pnpm-lock.yaml
Reverts CrisisCleanup/crisiscleanup-4-web#942
=> Revert "fix(deps): update dependency vue-router to v4.3.3"

src/pages/dashboards/DashboardPage.vue
- **fix: fixed the footer not dropping to the bottom of the screen**
=> Fix: Fix dashboard footer

src/components/work/WorksiteImageSection.vue, src/components/work/WorksiteSearchInput.vue
Issue: Cannot approve case request
Issue: Work search bar z index is on top of incident dropdown, gray overlay, etc.
=> Issue: Try to delete the image: Won't work

src/components/UserProfileCard.vue, src/components/chat/Chat.vue, src/pages/dashboards/DashboardPage.vue, src/pages/dashboards/DashboardSelector.vue, src/pages/dashboards/PhoneVolunteerDashboard.vue, src/pages/unauthenticated/PewPew.vue, test/e2e/pages/user-profile.test.ts
- **fix(pages): remove continue btn on dashboard selector, navigate to dashboard on tile click, improve styling**
- **fix(pages): improve dashboard selector heading, styling & responsiveness**
- **fix(pages): fix dashboard selector page layout, set main container height**
- **fix(pages): remove incident id from dashboard selector banner**
- **fix(pages): fix sticky footer on dashboard, improve layout**
- **fix(comps): add margin on user org & lang in UserProfileCard**
- **fix(pages): fix double scroll on default dashboard**
- **fix(pages): fix pewpew hotlines layout, add | separator, other improvements**
- **fix(comps): use fa icon for chat org toggle arrow**
- **test(e2e): fix user profile data-testid e2e tests**
=> fix: E2e test fixes, other issue fixes

src/components/work/WorksiteActions.vue, src/layouts/Authenticated.vue, src/models/types/index.ts, src/pages/Work.vue, src/utils/map.ts, src/utils/worksite.ts
Add functionality to track user locations using geolocation API and store them in the backend. Integrate user location display on the map with interactive markers and popups showing user details.
=> feat: add user location tracking and display feature

src/components/phone/PhoneOverlay.vue, src/components/work/WorksiteSearchAndFilters.vue, src/components/work/WorksiteSearchInput.vue, src/pages/dashboards/PhoneVolunteerDashboard.vue, src/pages/organization/CreateTeamModal.vue, src/pages/unauthenticated/PewPew.vue, src/pages/unauthenticated/disasters/DisasterDetail.vue, src/pages/unauthenticated/disasters/Disasters.vue, src/utils/helpers.ts
- **fix(pages): format ani closing date in this fmt `Friday, August 30, 2024 (in a day)`**
- **fix(pages): add hotline related utils, show closing date on DisasterDetail**
- **fix(pages): make /disasters page mobile responsive**
- **fix(pages): replace stats on PhoneVolunteerDashboard w/ GeneralStats**
- **fix(pages): let news section take full height instead of double scrollbar**
- **fix(pages): maybe fix localizations on pewpew page**
- **fix(phone): show unread & urgent unread message badges in PhoneOverlay**
- **fix(comps): add onWorksiteSearch emit w/ worksite results on WorksiteSearchInput**
- **fix(comps): pass onWorksiteSearch emit from WorksiteSearchAndFilters**
- **fix(pages): use WorksiteSearchAndFilters for adding cases while creating team**
Please check the type of change …
=> fix: Issue fixes 3

src/components/dashboard/DownloadAppBannerTeams.vue, src/pages/Work.vue, src/pages/dashboards/CommandCenterDashboard.vue, src/pages/dashboards/DashboardSelector.vue, src/pages/unauthenticated/disasters/Disasters.vue
Integrate user location layers with detailed popup information on the map. Add a DownloadAppBannerTeams component to promote the mobile app to team members.
=> feat: add user location layers and DownloadAppBanner component

src/components/admin/incidents/IncidentAssetBuilder.vue, src/components/phone/Agent.vue, src/components/work/WorksiteForm.vue, src/pages/dashboards/CommandCenterDashboard.vue
Change CommandCenterDashboard link to point to teams page. 
Add share text field in IncidentAssetBuilder and import necessary components. 
Clear location fields in WorksiteForm when closing worksite. 
Modify Agent component to use startTakingCalls action that emits an event.
=> refactor: update navigation links, forms, and event handling

src/components/HotlineNumber.vue, src/components/SocialLinks.vue, src/main.ts, src/pages/unauthenticated/Blog.vue, src/pages/unauthenticated/disasters/DisasterDetail.vue, src/pages/unauthenticated/disasters/Disasters.vue, src/pages/unauthenticated/disasters/DisastersArchived.vue
- feat(comps): add SocialLinks component (be65fe12)
- feat(pages): show social links on blog page header (3dc60124)
- fix(main): enable fontawesome brand icons for app (c08defc6)
- fix(pages): sort archived disasters by recents first (7fb65db1)
- feat(pages): add ability to copy hotline phone number to clipboard on DisasterDetail (1a4d624c)
- fix(pages): improve copy to clipboard logic for DisasterDetail (3da886b3)
- refactor(pages): extract hotline number pill logic to HotlineNumber component (7f579d26)
- fix(comps): improve copy hotline functionality in HotlineNumber (c610bfad)
- fix(pages): use HotlineNumber component in Disasters.vue (f2b59c55)
- fix(pages): refetch assets before downloading to avoid expired asset link on DisasterDetail (13120fcb)
- fix(pages): use solid download …
=> fix: Disaster page fixes, other minor fixes

src/components/chat/Chat.vue, src/components/phone/GeneralStats.vue, src/components/phone/PhoneCmsItems.vue
- Update callback interval in GeneralStats.vue from 30s to 60s
- Modify user refresh interval in Chat.vue from 1s to 10s
- Change news fetch interval in PhoneCmsItems.vue from 1min to 5mins
=> chore: Adjust intervals for performance optimization

src/pages/home/RegisterOrganization.vue
- Change interpolation method to v-html for 'choose_a_disaster'
=> feat(register-organization): improve disaster selection rendering

src/components/chat/Chat.vue, src/components/chat/ChatMessage.vue, src/pages/dashboards/DefaultDashboard.vue, src/services/db.service.ts
- Add USER_DATABASE constant
- Update database version to 7 for adding USER_DATABASE store
- Implement user data caching in IndexedDB
- Enhance `ChatMessage` component to use user data from IndexedDB
- Cache user data from API responses in IndexedDB in `DefaultDashboard` and `Chat` components
=> User loading performance

src/components/chat/Chat.vue, src/components/user/DetailsTooltip.vue, src/pages/dashboards/DefaultDashboard.vue
- **DetailsTooltip.vue:**
- Import `DbService` and `USER_DATABASE`
- Add caching mechanism to retrieve user data from local storage before making an API call
- Store user data in local storage after successful API fetch
- **DefaultDashboard.vue:**
- Introduce flags and queues to manage concurrent user data fetch requests
- Ensure queued requests are processed in order after the current request completes
- **Chat.vue:**
- Implement similar flags and queues to handle concurrent user data fetch requests
- Process subsequent requests from the queue after the ongoing request finishes
=> **feat:** enhance user data fetching robustness and efficiency

src/pages/home/Training.vue, test/e2e/pages/training.test.ts
Remove calldown video. Update test
=> Update training video

src/components/chat/Chat.vue, src/pages/dashboards/DefaultDashboard.vue
- **Remove:** Redundant request queue and flags for tracking ongoing requests in `getUsersById` function in both `DefaultDashboard.vue` and `Chat.vue`.
- **Change:** Update user online status check interval from 10 to 30 seconds in `Chat.vue`.
=> refactor: simplify getUsersById logic and modify polling interval

src/components/chat/Chat.vue, src/pages/dashboards/DefaultDashboard.vue
- Commented out user fetch API calls in DefaultDashboard.vue
- Commented out user fetch API calls in Chat.vue
- Reduced polling interval for online users from 30_000ms to 10_000ms in Chat.vue
=> fix: comment out user fetch API calls and adjust polling interval

src/components/chat/Chat.vue, src/components/phone/PhoneCmsItems.vue, src/pages/OtherOrganizations.vue
- **refactor:** replaced `Table` component with `AjaxTable` for dynamic data fetching
- **refactor:** updated table data source to use `url` prop instead of static `data`
- **refactor:** removed unused features such as pagination and sorting
- **chore:** cleaned up commented and redundant code
- **fix:** added null safety check to group users by organization in `Chat.vue`
- **fix:** ensured default value when emitting unread message count in `Chat.vue`
- **fix:** ensured default value when emitting unread urgent message count in `Chat.vue`
- **fix:** ensured default value when emitting unread message count in `PhoneCmsItems.vue`
=> Commit message

src/components/navigation/NavButton.vue, src/components/work/CaseFlag.vue, src/components/work/CaseHistory.vue, src/components/work/WorksiteFilters.vue, src/components/work/WorksiteForm.vue, src/components/work/WorksiteImageSection.vue, src/components/work/WorksiteNotes.vue, src/pages/unauthenticated/Survivors.vue, src/router.ts
- **fix(comps): hide `Use My Location` btn on phone page in WorksiteForm**
- **fix(router): remove duplicate dashboard route, fix nested dashboard route names to fix active navitem indicator**
- **fix(comps): remove router-link active classes from NavButton to show correct active nav btn indicators**
- **fix(i18n): fix localization on WorksiteFilters**
- **fix(comps): add disableImageUpload prop to WorksiteImageSection**
- **feat(pages): disable image upload + add warning for outdated incidents on Survivors**
- **fix(comps): keep note add field on by default on worksite form**
- **fix(comps): remove invalid `/cases/new` route on error / invalid incident id for CaseHistory & CaseFlag**
=> fix: minor issue fixes

src/components/phone/PhoneNews.vue
- Change news refresh interval from 10 seconds to 5 minutes
=> fix: adjust news update interval in PhoneNews.vue

src/layouts/Authenticated.vue
- **feat**: reload page on router error to ensure navigation completion
=> - **fix**: handle dynamic import errors in router

src/components/work/WorksiteForm.vue, src/components/work/WorksiteNotes.vue, src/components/work/WorksiteSearchInput.vue, src/components/work/WorksiteView.vue, src/pages/unauthenticated/Survivors.vue, tailwind.config.cjs
- **fix(work): set addingNotes with expanded prop disabled by default, update usages**
- **fix(tailwind): add search-dropdown custom z-index value in tailwind config**
- **fix(comps): use z-search-dropdown on WorksiteSearchInput to set it above phone overlay**
- **fix(comps): add error handling on selected-geocode emit usages**
=> fix: Worksite search input zindex fixes, other minor fixes

.github/workflows/main.yml, package.json, pnpm-lock.yaml, src/components/ImageModal.vue, src/components/WorksiteFeed.vue, src/components/WorksitePhotoMap.vue, src/components/header/UserProfileMenu.vue, test/e2e/pages/user-profile.test.ts
- **fix(comps): auto hide profile menu on menu item click**
- **test(e2e): remove profileMenu click on profile since it auto hides on click now**
- **ci(main): run smoke e2e tests against development instead of staging**
=> fix: Replace staging with development for smoke e2e tests

src/pages/phone/PhoneSystem.vue
- Rename `manualOutboundBlock` to `callsBlocked` for clearer semantics
- Move call blocking logic to a new `blockCalls` function
- Enhance `onLoggedIn` function to use `blockCalls`
- Update watcher to block calls until agent is ready
- Add detailed JSDoc comments for `onLoggedIn`
=> feat(phone-system): update call blocking mechanism

src/components/work/WorksiteForm.vue
Show an error when coordinates are missing while saving a Case
=> Show error message when lat-lng is not set when saving Case

src/components/Table.vue, src/components/work/WorksiteForm.vue
- **refactor(comps): remove debug log from Table**
- **fix(comps): handle undefined geocoder parts when updating worksite fields**
=> fix: Fix undefined geocoder parts issue

src/components/work/WorksiteForm.vue, src/components/work/WorksiteView.vue, src/pages/phone/PhoneSystem.vue
- **fix(comps): show worksite flags on WorksiteForm, hide empty space when header content is empty**
- **fix(comps): set auto size for worksite form & view header**
- **fix(pages): use same width for worksite form section as work page in phone page**
=> fix: Show worksite flags on view and form, improve layout

src/components/AddressDisplay.vue, src/components/CopyText.vue, src/components/IncidentContact.vue, src/components/PhoneNumberDisplay.vue, src/components/dashboard/DashboardFooter.vue, src/components/work/WorksiteForm.vue, src/components/work/WorksiteView.vue, src/filters/index.ts, src/pages/admin/ZendeskTicketDashboard.vue, src/pages/phone/PhoneSystem.vue, src/pages/unauthenticated/PewPew.vue, src/pages/unauthenticated/disasters/DisasterDetail.vue, src/pages/unauthenticated/disasters/Disasters.vue, src/utils/helpers.ts, test/unit/components/AddressDisplay.test.ts, test/unit/components/CopyText.test.ts, test/unit/components/PhoneNumberDisplay.test.ts, test/unit/utils/helpers.test.ts
- **refactor(comps): rename HotlineNumber to PhoneNumberDisplay, update usages**
- **feat(comps): add CopyText component**
- **fix(comps): use CopyText in PhoneNumberDisplay component**
- **fix(comps): set more padding on icon in CopyText**
- **feat(utils): add worksite address helpers, add generateGoogleMapsLink**
- **feat(comps): add AddressDisplay component**
- **feat(comps.work): use AddressDisplay to show copyable & linked address on WorksiteForm & WorksiteView**
- **fix(utils): handle empty worksite in formatWorksiteAddressHtml**
- **test(unit): add unit tests for util helpers**
- **test(unit): add unit tests for CopyText component**
- **fix(comps): convert phoneNumber to string before formatting in PhoneNumberDisplay**
- **test(unit): add unit tests for PhoneNumberDisplay & …
=> feat: Add AddressDisplay, CopyText, update all phone num refs, other improvements

src/components/work/WorksiteForm.vue
=> fix(comps.work): auto save note when editing worksite since its easy to forget to hit save button

src/components/ColoredCircle.vue, src/components/SimpleMap.vue, src/components/UpdateCaseStatus.vue, src/components/WorksiteLegend.vue, src/components/WorksiteStatusDropdown.vue, src/components/modals/ChangeOrganizationModal.vue, src/components/work/WorksiteNotes.vue, src/components/work/WorksiteTable.vue, src/hooks/useCurrentUser.ts, src/models/Role.ts, src/pages/Work.vue, src/pages/phone/PhoneSystem.vue, src/pages/phone/routes.ts
- **fix(pages): add worksite edit route on phone page, jump to case on page load if ws id exists**
- **fix(pages): auto jump to case when ws id is available on route on work page**
- **fix(comps): add ColoredCircle component**
- **fix(comps): update all badge usages used to show circle to use ColoredCircle**
- **refactor(comps): improve WorksiteLegend layout & its usage in SimpleMap**
- **fix(comps): auto hide WorksiteLegend when it goes out of bounds of SimpleMap**
- **feat(models): add helpers to Role vuex model**
- **feat(hooks): add isPhoneAgent, addUserRole helper to useCurrentUser hook**
- **feat(phone): add ensurePhoneAgentRole call to PhoneSystem to make user phone agent if missing**
=> fix: Minor bug fixes

src/components/IncidentContact.vue, src/components/PhoneNumberDisplay.vue, src/components/phone/ManualDialer.vue, src/components/phone/PhoneOverlay.vue, src/components/work/WorksiteForm.vue, src/pages/phone/PhoneSystem.vue, src/pages/unauthenticated/PewPew.vue
- **feat(comps): add plain or styled type to PhoneNumberDisplay**
- **fix(app): use plain PhoneNumberDisplay on PewPew & IncidentContact**
- **fix(comps): use PhoneNumberInput for manual dialer**
- **fix(comps): show formatted phone number on PhoneOverlay green screen**
- **feat(app): collapse green screen on call details when user tries to search on phone page or worksite form**
- **fix(pages): read prefill data on PhoneSystem to fill caller phone num on WorksiteForm**
=> fix: Prefill phone, auto hide green screen, other phone related fixes

src/components/phone/PhoneDoctor.vue
- Refactor `phoneService.dial` to use reactive `HOTLINE_PHONE_NUMBER`
- Update `PhoneDoctor.vue` phone initiation process
=> feat(phone): enhance phone dials with reactive hotline number

src/components/phone/PhoneDoctor.vue, src/components/phone/PhoneOverlay.vue, test/unit/components/phone/PhoneDoctor.test.ts
- Simplify sections computation by removing isAdmin check in PhoneOverlay.vue.
fix(phone-doctor): refactor string concatenations
- Simplify error and description strings in PhoneDoctor.vue by removing unnecessary line breaks.
- Correct multi-line string definitions for better readability.
test(phone-doctor): update unit tests for consistency
- Adjust test strings to match updated text in PhoneDoctor.test.ts.
- Update button text check to align with new localization keys.
=> feat(phone-doctor): Phone Doctor General Availability

src/components/phone/PhoneDoctor.vue
- import BaseSelect component and formatCmsItem helper function
- add state management for carrier selection and remediation extraction
- fetch and initialize dropdown items from CMS on component mount
- update error section layout to use grid and fix toggling logic for issues
- introduce BaseSelect dropdown for carrier selection and display remediation content
=> feat: Add carrier dropdown and remediation logic to PhoneDoctor component

src/pages/phone/PhoneSystem.vue
- Redirect to phone page after clearing case
=> fix(phone-system): enhance clearCase function

src/components/locations/LocationTool.vue, src/components/work/WorksiteFilters.vue, src/hooks/worksite/useWorksiteMap.ts
- **refactor:** Add dynamic map ID parameter to `useWorksiteMap` to handle multiple maps.
- **style:** Adjust `WorksiteFilters` Vue component grid layout for better UI structure.
- **feat:** Integrate a new button in `WorksiteFilters` to create and draw locations on the map.
- **refactor:** Update LocationTool component to use a unique map ID.
=> feat: Enhance Worksite Map Integration and Improve Location Filters

src/pages/admin/AdminGodMode.vue
- Handle optional point coordinates and nullable updated_at
- Ensure only the latest location per user is retained
=> feat(AdminGodMode.vue): Optimize user location processing

src/pages/admin/AdminGodMode.vue
- Fetch users in chunks with Promise.all for improved performance
- Divide user IDs into smaller batches of 100 for API requests
=> refactor: optimize user data retrieval in AdminGodMode.vue

src/pages/admin/AdminGodMode.vue
- Add `fields` parameter to the API call for fetching user details
=> feat: enhance user data fetching in AdminGodMode

src/pages/admin/AdminReportGenerator.vue
- Add `w-180` class to main container for consistent width
- Display selected report description below report selector
- Use `input.description` as placeholder for a more contextual input
- Compute selected report object to fetch and display description
- Fetch and include report description in available reports data
=> feat(admin): enhance report generator with descriptions

src/pages/OtherOrganizations.vue, src/pages/admin/AdminSendBulkEmail.vue, src/pages/admin/AdminSendBulkSms.vue
- Append each valid number individually to formData
fix(AdminSendBulkEmail.vue): refactor email appending method
- Append each valid email individually to formData
fix(OtherOrganizations.vue): update table URL and height styling
- Set table URL to '/other_organizations'
- Adjust table body height to '40rem'
feat(OtherOrganizations.vue): add overdue_count column with navigation
- Implement button to navigate to incidents for overdue counts
refactor(OtherOrganizations.vue): re-enable columns for organization metrics
- Reactivate columns for incidents, cases_reported, cases_claimed, cases_closed, cases_overdue, and last_login
```
=> fix(AdminSendBulkSms.vue): refactor phone number appending method

src/components/DisplayLocation.vue, src/pages/OtherOrganizations.vue
- Add loading spinner
- Introduce toggleable checkbox list for table columns
- Update table with row details and search enablement
- Implement multi-level primary contacts display in row details
- Replace old Table component with AjaxTable
- Refactor columns with dynamic metadata fetching
- Add column visibility toggling functionality
=> feat: Major overhaul of OtherOrganizations.vue 

src/hooks/useInviteUsers.ts, src/models/User.ts, src/pages/OtherOrganizations.vue, test/unit/models/User.test.ts
- Add support for unique invitation keys in User model
- Implement sendInvitationReport method in User model
- Integrate unique key generation using generateUUID in useInviteUsers hook
- Ensure invitation report is sent after inviting users
=> feat: enhance user invitation process

src/components/CapabilityMatrix.vue, src/pages/OtherOrganizations.vue
- Introduce capability matrix component to display capabilities in a structured table format
- Add `showCapabilities` method to handle displaying the capabilities modal
- Update `OtherOrganizations.vue` to include capabilities button and functionality
- Import `CapabilityMatrix.vue` in `OtherOrganizations.vue` to manage component data and actions
This enhancement allows users to view organization capabilities in a modal with improved readability.
=> feat: add capabilities display feature

src/components/downloads/DownloadWorksiteCsv.vue, src/pages/Downloads.vue, src/pages/Work.vue, src/utils/downloads.ts
- Add `forceFileDownloadFromURl` utility function for better file download handling.
- Replace `base-link` with `base-button` in `Downloads.vue` for initiating file downloads.
- Introduce `DownloadWorksiteCsv` component to manage async file downloads with a modal UI.
- Update `Work.vue` to integrate `DownloadWorksiteCsv` for processing and downloading CSV files dynamically.
- Refactor and improve user feedback during file download processes.
=> feat: enhance file download functionality and refactor UI

src/pages/Work.vue, src/pages/phone/PhoneSystem.vue
- Refactored download functionality to use switch case for response status handling in `PhoneSystem.vue` and `Work.vue`.
- Added error feedback for unexpected response statuses indicating potential oversized downloads.
- Enhanced user experience by modifying download confirmation and fallback logic for various response statuses.
- Removed unnecessary debug log from `PhoneSystem.vue`.
=> feat: improve download handling and error feedback

src/pages/Downloads.vue, src/pages/Work.vue
- Add bulk delete functionality with selection-enabled table
- Introduce edit download name feature
- Update table UI with status badges and additional actions
- Replace buttons with `ccu-icon` components for consistency
- Implement reloadTable function for dynamic updates
- Refactor method names and component imports for clarity
fix(work): adjust download endpoint to synchronous version
=> feat(downloads): enhance downloads page with new features

.github/workflows/e2e.yml, .github/workflows/main.yml, package.json, pnpm-lock.yaml, src/components/scheduling/AddScheduleDialog.vue, src/components/scheduling/EditScheduleDialog.vue, src/components/scheduling/WorkTypeScheduleMap.vue, src/components/scheduling/WorksiteCalendar.vue, src/models/Team.ts, src/models/types/index.ts, src/pages/Work.vue, test/unit/components/scheduling/AddScheduleDialog.test.ts
- **Team Model Updates**: Added `color` field to the `Team` model for team-based calendar color coding.
- **Work Types Enhancements**: Introduced support for nested work types within `WorkTypeSchedule`, displaying additional case details (e.g., multiple work types) in scheduling components.
- **Scheduling Calendar Features**: Integrated `@schedule-x/calendar-controls` for advanced calendar controls and unified time slot rounding.
- **Improved Team Calendar Integration**: Dynamically set team-specific colors on calendar views based on the `color` attribute from the Team model.
- **UI/UX Improvements**: Enhanced worksite scheduling UI, clarified view labels, and added nested work type information to interactive components like maps and dialogs.
- **Data Exports**: Simplified export logic …
=> feat(scheduling): enhance scheduling features with nested work types and team-based calendars

src/pages/admin/Index.vue
- Updated the data fetching logic in Index.vue to utilize destructured responses from the API for bug reports and ticket counts.
- Implemented reactive handling of data updates using the `whenever` function to ensure that the UI reflects the latest data state.
- Enhanced code readability and maintainability by removing unnecessary conditional checks.
Overall: This commit refines the data fetching process for the admin dashboard, improving responsiveness and clarity in the codebase.
=> refactor(Index.vue): improve bug and ticket data fetching logic

src/components/work/WorksiteNotes.vue, src/pages/Calendar.vue, src/pages/WorksiteNavigationIcons.vue, src/pages/admin/AdminSentimentAnalysis.vue
- Simplified note class assignment by introducing a `getNoteClass` method for better readability and maintainability.
- Improved AI-generated note previews with a toggle feature for expanded view, enhancing user experience.
- Updated layout for survivor and volunteer notes to improve visual clarity and interaction.
- Removed redundant click handlers and streamlined the note expansion logic for better performance.
These changes enhance the usability and visual presentation of worksite notes, making it easier for users to interact with and understand the content.
=> refactor(WorksiteNotes.vue): enhance note display and interaction features

src/components/phone/EditAgentModal.vue
This PR is setup to fix issues in the edit agent modal not saving  any changes for phone number and laanguages
=> Edit Agent Modal: Fix Issue with languages not updating

src/pages/home/About.vue
=> fix(pages): fix page layout and formatting for about page
