CrisisCleanup/crisiscleanup-4-web

- package.json
- pnpm-lock.yaml
- src/utils/oauth.ts
- feat(deps): add crypto-js
- fix(utils.oauth2): support sha256 hashing in non-secure (http) environments
Authorization code flow fails during local development because web crypto subtle api is only available in secure (https) environments.
We only need this to perform the sha256 hash.
See: https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto
No longer requires https to succeed in local/non-secure env due to sha256 hash.
> fix(utils.oauth2): support sha256 hashing in non-secure (https) browser environments

- .eslintrc.cjs
- src/components/locations/LocationTool.vue
- src/components/work/WorksiteForm.vue
- src/components/work/WorksiteSearchInput.vue
- src/hooks/useRecentWorksites.ts
- src/models/WorkType.ts
- src/models/Worksite.ts
- src/store/database.ts
- fix(comps): set getter func on watch calls with props.* as they were not running
- refactor(comps): set emits option for WorksiteSearchInput
- feat(models): add `WorkType` model
- chore: disable typescript-eslint/member-ordering rule
- feat(store): register WorkType model in vuex store
- fix(models): set WorkType as work_types type in Worksite model
- fix(comps): fix type + other issues with WorksiteSearchInput
- refactor(comps): split onFocus into func in WorksiteSearchInput
- fix(models): remove id and updated_at fields from Worksite model as its inherited from CCUModel
- feat(hooks): add useRecentWorksites composable
- fix(comps): fix issues + refactor `WorksiteSearchInput`
- fix(comps): add debounce search to `WorksiteSearchInput`, fix types
- feat(comps): disable recent worksites …
> fix: Fix issues with Worksite search input, add debounce + other improvements, wip recent worksites

- src/pages/Work.vue
-changed 0 to .990 to show the most vulnerable on 0 and allowed it to reach 100
closes #499
> fix(work): svi slider cant reach 100, and 0 shows everything

- src/hooks/useRAG.ts
- src/pages/admin/AdminRAG.vue
- feat(hooks/useRAG): extract and expose `fetchConversations` from `useRAGConversations`
- feat(hooks/useRAG): track message streaming state, expect new unchunked results
- fix(pages/admin/rag): resolve subsequent messages on new convos creating more convos instead of continuing
> fix(rag): resolve subsequent messages on new convos creating new convos instead of continuing

- src/components/admin/incidents/IncidentLocationEditor.vue
- src/pages/admin/AdminIncidentWizard.vue
[Peek 2024-01-12 15-31.webm](https://github.com/CrisisCleanup/crisiscleanup-4-web/assets/46167867/d325051a-ee7d-4ad6-a6dd-766d07d2cb68)
Ref: #128 
> fix(pages/admin): fix layer name autofill from incident name for admin incident wizard

- src/pages/admin/AdminRAG.vue
`inform.svg` icon was recently inverted / edited.
This caused prevented it from being visible in rag messages since the new icon is now the same color as the background where its used.
This just updates the usage to invert the icon color and increase the size.
> fix(pages/admin/rag): accomodate changes made to `inform` icon used in rag message tools window

- src/layouts/Home.vue
Since the issue was primarily in staging and in prod I believe that the issue mainly is the pathing for the link for the logo. I changed the path to be based on the src folder instead of using ../assets which might have caused problems
> fix(login): image link for logo

- src/components/BaseInput.vue
- src/components/work/WorksiteNotes.vue
Make Worksite Notes Field Grow when Typing #796 
@aarontitus @deepanchal 
Previous behavior: The text input field for notes was too small and included scrollbars, lacking the ability to auto-resize.
reference video: https://gyazo.com/2216bf02cc23942f9883dfd7219a1ca0
New behavior: The BaseInput component now features an optional textAreaResize boolean that enables auto-resizing for text areas. Consequently, the text areas for notes on worksites and phone now automatically adjust in size as the user types.
reference video: https://gyazo.com/2216bf02cc23942f9883dfd7219a1ca0
> feat: added textarea resize to baseinput

- src/components/Tag.vue
- src/components/UserEquipmentSelect.vue
- src/components/UserProfileSection.vue
- src/models/types/index.ts
- src/pages/UserProfile.vue
- src/router.ts
- test/e2e/pages/user-profile.test.ts
- Updated `Tag.vue` to allow dynamic classes for more flexible styling.
- Improved `UserEquipmentSelect.vue` to use localized equipment names (`name_t`) and fixed equipment fetching logic.
- Added `UserProfileSection.vue` component to encapsulate expandable sections in the user profile page.
- Updated `UserProfile.vue` to include new sections and enhanced data bindings for user details, social media, and beta features.
- Modified the end-to-end test in `user-profile.test.ts` to align with the new component structure and IDs.
- Added `BetaFeature` interface in `types` to support new beta features functionality.
- Updated router to load `UserProfile.vue` instead of the old `Profile.vue`.
> feat(user-profile): enhance user profile UI and functionality

- src/components/SimpleMap.vue
- src/components/WorkTypeMap.vue
- src/components/accordion/Accordion.vue
- src/components/accordion/AccordionItem.vue
- src/components/dashboard/TeamCompletion.vue
- src/components/locations/LayerUploadTool.vue
- src/components/work/WorksiteView.vue
- src/main.ts
- src/models/PhoneOutbound.ts
- src/models/Team.ts
- src/pages/dashboards/CommandCenterDashboard.vue
- src/pages/dashboards/DashboardSelector.vue
- src/pages/organization/Affiliates.vue
- src/pages/organization/TeamDetail.vue
- src/pages/unauthenticated/InvitationSignup.vue
- src/pages/unauthenticated/Survivors.vue
- src/router.ts
- test/unit/components/accordion/__snapshots__/AccordionItem.test.ts.snap
feat(ui): improve map components and introduce Command Center dashboard
- Added `removeLegend` prop to `SimpleMap.vue` to control legend visibility.
- Refactored `WorkTypeMap.vue` to remove unused `ref` and simplify map initialization.
- Enhanced `AccordionItem.vue` with `iconPosition` and `startOpen` props for improved flexibility.
- Introduced `CommandCenterDashboard.vue` to display affiliated teams and related statistics.
- Updated `Team.ts` model to include `organization` field.
- Added `TeamCompletion.vue` to visualize team completion metrics in dashboards.
- Conditional API calls in `Affiliates.vue` to optimize network requests.
- Updated routing to include the new Command Center dashboard.
chore: Better global error handling for axios calls
> feat(ui): improve map components and introduce Command Center dashboard

- src/main.ts
- src/pages/dashboards/CommandCenterDashboard.vue
Include 'limit' and 'incident' as parameters to refine the API request, thereby enhancing the relevance and efficiency of fetched data. This update helps in limiting the results and associating them with the current incident.
> feat: add query parameters to getAffiliates API call

- src/components/phone/GeneralStats.vue
- src/models/PhoneOutbound.ts
Convert string values to numbers in GeneralStats.vue and PhoneOutbound.ts to prevent potential type issues. This will enhance data reliability and prevent type errors during computations.
> fix: ensure numeric casting for stats and phone counts

- src/components/SimpleMap.vue
- src/hooks/worksite/useWorksiteMap.ts
- src/pages/Work.vue
- Add toggle button for changing map layers in SimpleMap.vue
- Introduce `showMapLayerToggle` prop to control visibility of the button
- Implement `toggleMapType` method in Work.vue to handle layer switching
- Enhance `useWorksiteMap.ts` with functionality to switch between multiple map layers
> feat: add map layer toggle button

- src/components/work/WorksiteView.vue
- Include current organization's ID when filtering work types claimed by organization
- Exclude current organization's ID when filtering work types not claimed by affiliates
> feat: update work type claiming logic

- src/components/phone/ManualDialer.vue
- Add moment.js for date and time handling
- Introduce 'after10pmEastern' computed property
- Update button disabled condition to include 'after10pmEastern'
> fix: disable dial button after 10 PM Eastern time

- src/pages/phone/PhoneSystem.vue
- test/unit/models/Organization.test.ts
- Removed the 'data-prefill' prop from the PremadeComponent at index 431
- Removed the 'data-prefill' prop from the PremadeComponent at index 692
> refactor(phone): remove unused data-prefill prop in PhoneSystem.vue

- src/hooks/worksite/useRenderedMarkers.ts
On work page, when user selects a filter for organization response area, the dots on
the map look the same. The filtered out dots have lower opacity but they have same texture.
This was caused by having same cache key with texture caching for filtered and visited worksites.
> fix(hooks): fix bug with response area worksites filtering not showing correct filtered dots bc of texture caching error

- src/components/phone/PhoneDoctor.vue
- Replace text interpolation with v-html to render carrierRemediation with HTML in PhoneDoctor.vue
> fix: render carrier remediation with HTML

- src/components/phone/CurrentCall.vue
- src/components/work/WorksiteFilters.vue
- src/utils/data_filters/WorksiteLocationsFilter.ts
- test/unit/utils/data_filters/WorksiteLocationsFilter.test.ts
- add primary and secondary location fields in WorksiteLocationsFilter.test.ts
- consolidate locations into a single 'locations' key in WorksiteLocationsFilter.ts
- update CurrentCall.vue to fetch worksites for the phone number within the last 60 days
- enhance WorksiteFilters.vue with a multi-select for search locations and location types
- implement search functionality for locations in WorksiteFilters.vue
> feat: enhance WorksiteFilters and location filter logic

- src/pages/admin/AdminGodMode.vue
- import 'moment' for date manipulation
- add date filter to API request for the last 30 days
- include 'organization' and 'files' fields in user details API request
> feat(AdminGodMode.vue):

- src/pages/Work.vue
- src/pages/phone/PhoneSystem.vue
- src/utils/dashboard.ts
- src/utils/worksite.ts
- Refactor `loadCasesCached` to `loadCasesCachedWithPagination` for enhanced pagination support.
- Implement `loadCasesPaginated` function to handle API requests with pagination.
- Update method invocations in PhoneSystem.vue, Work.vue, and dashboard.ts to use the new `loadCasesCachedWithPagination`.
- Improve cache reconciliation logic to ensure data consistency.
> feat: add pagination support to load cases

- src/components/phone/ManualDialer.vue
- Add `hasActiveHotline` computed property to ensure a hotline is active before allowing dial functionality.
- Import `useActiveHotlines` to check for active hotline incidents.
- Update button `:disabled` logic to include `hasActiveHotline`.
- Optimize imports by removing unused `useI18n` and `useEmitter`.
> feat(manual-dialer): add hotline validation

- src/pages/Work.vue
- Adjust debounce delay from 1000ms to 500ms for faster response.
- Add `leading: true` option to trigger immediate execution on the first call.
> feat: improve onLocationSearch debounce behavior

- src/components/work/WorksiteForm.vue
- src/models/Worksite.ts
- Implemented `sendEmail` method in WorksiteForm for sending emails to survivors.
- Added email icon to the email input field, dynamically displayed based on conditions.
- Integrated confirmation dialog when triggering email sending.
- Added `sendSurvivorEmail` API method in Worksite model to handle email requests.
> feat: add functionality to send emails from WorksiteForm

- src/pages/Work.vue
- Prompt users with a confirmation dialog for downloads with over 2500 records
- Default to synchronous download when record count is small or user cancels
- Preserve asynchronous download for large downloads upon user confirmation
> feat: add confirmation for large CSV downloads

- src/components/PdfViewer.vue
- src/pages/admin/AdminMagazine.vue
- src/pages/unauthenticated/Magazine.vue
This PR implements several significant improvements to our magazine functionality:
1. **Enhanced PDF Viewer Component**
- Added pagination controls with page navigation
- Centered PDF content and improved responsive layout
- Added events for tracking page changes
2. **Restructured Magazine Data Model**
- Migrated from "issues" to "editions" terminology
- Added support for primary/secondary editions with thumbnail images
- Improved metadata with incident IDs, timeframes, and better organization
3. **Redesigned Public Magazine Page**
- Created a modern, engaging layout highlighting latest issue
- Added separate sections for primary and secondary editions
- Improved download and reading experience with modal viewer
- Updated `PdfViewer.vue` to support pagination and emit page change events
- …
> PDF Viewer Pagination and Magazine Editions Overhaul

- src/pages/admin/AdminSentimentAnalysis.vue
- Changed the API endpoint from `/incidents` to `/incidents_list` to align with the new backend structure.
- Added query parameters to limit the fields fetched, set a limit of 200 results, and sort by the `start_at` field in descending order.
- This update improves data retrieval efficiency and ensures the component receives the necessary information for display.
> fix: update API endpoint and parameters for incident loading in Admin SentimentAnalysis
